In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from date_extraction import *

In [3]:
# Downloading or loading Project Gutenberg
raw_metadata_df, path_to_cached_gutenberg = load_gutenberg(your_path='/Users/eglantinevialaneix', DOWNLOAD=False)
metadata_df = clean_gutenberg(raw_metadata_df)

Successfully loaded the metadata dataframe.
Path to cached dataset files: /Users/eglantinevialaneix/.cache/kagglehub/datasets/lokeshparab/gutenberg-books-and-metadata-2025/versions/4/
Dropped 16402 books where Language ≠ english or Type ≠ Text.
Kept only 6 columns.

In [4]:
check_folder_size(path_to_cached_gutenberg)
check_memory_usage()

Folder size: 28.86 GB
Total memory: 460.43 GB
Memory used: 286.96 GB = 62.32 %
Free memory: 173.47 GB = 37.68 %

In [5]:
path_to_enormous_jsonl = "../../../../Downloads/history/ChronobergDataset.jsonl"
print(f"The Chronoberg Dataset file takes {os.path.getsize(path_to_enormous_jsonl) / 1e9:.2f} GB of memory.")
df_chronoberg = load_chronoberg_json(path_to_enormous_jsonl)
df_chronoberg

The Chronoberg Dataset file takes 10.40 GB of memory.

shape: (249, 2)
┌──────┬───────────────────────────────┐
│ year ┆ text                          │
│ ---  ┆ ---                           │
│ i64  ┆ str                           │
╞══════╪═══════════════════════════════╡
│ 1979 ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆ Transcriber's note:           │
│      ┆                               │
│      ┆ Exten…                        │
│ 1753 ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                LETTERS TO…    │
│ 1789 ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆ Persuasion                    │
│      ┆                               │
│      ┆                               │
│      ┆ by Jane Auste…                │
│ 1779 ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆ THE WRITINGS OF THOMAS PA…    │
│ 1844 ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆ THE LIFE OF FRANCIS MARIO…    │
│ …    ┆ …                             │
│ 1786 ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆   Henry Clay, "On the…        │
│ 1866 ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆ Transcribed from the 1894…    │
│ 1850 ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆ The Scarlet Letter            │
│      ┆                               │
│      ┆ by Nat…                       │
│ 1759 ┆                               │
│      ┆                               │
│      ┆ Transcribed from the 1889 Ca… │
│ 1990 ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                               │
│      ┆                      …        │
└──────┴───────────────────────────────┘

In [6]:
metadata_df

,Etext Number,Title,Bookshelves,Authors,rights,Subjects
0,1,The Declaration of Independence of the United ...,Politics; American Revolutionary War; United S...,"Jefferson, Thomas",Public domain in the USA.,E201 ; JK ; United States -- History -- Revolu...
1,2,The United States Bill of Rights\r\nThe Ten Or...,Politics; American Revolutionary War; United S...,United States,Public domain in the USA.,Civil rights -- United States -- Sources ; JK ...
2,3,John F. Kennedy's Inaugural Address,Browsing: History - American; Browsing: Politics,"Kennedy, John F. (John Fitzgerald)",Public domain in the USA.,E838 ; United States -- Foreign relations -- 1...
3,4,Lincoln's Gettysburg Address\r\nGiven November...,US Civil War; Browsing: History - American; Br...,"Lincoln, Abraham",Public domain in the USA.,E456 ; Soldiers' National Cemetery (Gettysburg...
4,5,The United States Constitution,United States; Politics; American Revolutionar...,United States,Public domain in the USA.,JK ; United States. Constitution ; United Stat...
...,...,...,...,...,...,...
75387,75563,"Cedar chests, how to make them",NaN,"Windoes, Ralph Flagg, 1891-1967",NaN,Chests
75388,75564,The puzzle of life,NaN,"Nicols, Arthur",NaN,NaN
75389,75565,The man with a grouch,NaN,"Stacpoole, H. De Vere (Henry De Vere), 1863-1951",NaN,NaN
75390,75566,Visibility—Zero,NaN,"Stearns, Myron M. (Myron Morris), 1884-1963",NaN,NaN
75391,75567,Highland annals,NaN,"Dargan, Olive Tilford, 1869-1968",NaN,NaN

In [7]:
metadata_df.columns

Index(['Etext Number', 'Title', 'Bookshelves', 'Authors', 'rights',
       'Subjects'],
      dtype='str')

In [8]:
all_book_ids = raw_metadata_df["Etext Number"].astype(int).to_list()
all_book_ids.sort()

all_books_filenames = os.listdir(path_to_cached_gutenberg + "/books")
all_books_filenames = [int(book_id) for book_id in all_books_filenames]
all_books_filenames.sort()


print("Number of books id in metadata: ", len(all_book_ids))
print("Number of books present in the dataset: ", len(all_books_filenames))
print("Delta = ", len(all_book_ids) - len(all_books_filenames))

all_books_filenames_set = set(all_books_filenames)
all_book_ids_set = set(all_book_ids)

missing_metadata = list(all_books_filenames_set - all_book_ids_set)
missing_files = list(all_book_ids_set - all_books_filenames_set)

print(f"Missing books in dataset: {len(missing_files)} among which {sum(metadata_df["Etext Number"].isin(missing_files))} are english text.")
print("Missing metadata: ", len(missing_metadata))

Number of books id in metadata:  75394
Number of books present in the dataset:  75370
Delta =  24
Missing books in dataset: 24 among which 22 are english text.
Missing metadata:  0

In [9]:
book_ids = metadata_df["Etext Number"][~metadata_df["Etext Number"].isin(missing_files)].to_list()
book_ids

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 51,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 115,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 128,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 228,
 230,
 232,
 233,
 234,
 235,
 236,
 238,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 633,
 634,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 ...]

In [10]:
path_to_fulltexts = "../../../../Downloads/history/opium_books_fulltext/"

In [11]:
with open(f"{path_to_cached_gutenberg}books/{book_ids[0]}", 'r') as f:
    print(f.read(2000))

*** START OF THE PROJECT GUTENBERG EBOOK 1 ***

===========================================================

     NOTE:  This file combines the first two Project Gutenberg
     files, both of which were given the filenumber #1. There are
     several duplicate files here. There were many updates over
     the years.  All of the original files are included in the
     "old" subdirectory which may be accessed under the "More
     Files" listing in the PG Catalog of this file. No changes
     have been made in these original etexts.

===========================================================


**Welcome To The World of Free Plain Vanilla Electronic Texts**

**Etexts Readable By Both Humans and By Computers, Since 1971**

*These Etexts Prepared By Hundreds of Volunteers and Donations*

Below you will find the first nine Project Gutenberg Etexts, in
one file, with one header for the entire file.  This is to keep
the overhead down, and in response to requests from Gopher site
keeper to eliminate as much of the headers as possible.

However, for legal and financial reasons, we must request these
headers be left at the beginning of each file that is posted in
any general user areas, as Project Gutenberg is run mostly by a
donation from people like you.

If you see our books posted ANYWHERE without these headers, you
are requested to send them a note requesting they re-attach the
header, otherwise they have no legal protection and we have the
loss of the donations we hope will keep Project Gutenberg going
long enough to post 10,000 books, plays, musical pieces, etc.



***START**THE SMALL PRINT!**FOR PUBLIC DOMAIN ETEXTS**START***
Why is this "Small Print!" statement here?  You know: lawyers.
They tell us you might sue us if there is something wrong with
your copy of this etext, even if you got it for free from
someone other than us, and even if what's wrong is not our
fault.  So, among other things, this "Small Print!" statement
disclaims most of our liability to you.  It

In [ ]:
# This cell takes approx. 40 min to run
results = pd.DataFrame(
    extract_books_fast(df_chronoberg, book_ids, f"{path_to_cached_gutenberg}books/"),
    columns=["year", "book_id"]
)

Loading fingerprints: 100%|██████████| 58970/58970 [00:16<00:00, 3669.76book/s]
Scanning Chronoberg rows: 100%|██████████| 249/249 [33:54<00:00,  8.17s/row, matched_books=32747/58889]

In [17]:
results

       year  book_id
0      1979    32771
1      1979    32772
2      1979    57347
3      1979    24582
4      1979    24586
...     ...      ...
32742  1759    38327
32743  1759    38444
32744  1759    39270
32745  1759    31339
32746  1990    52776

[32747 rows x 2 columns]

In [ ]:
#results.to_csv("../data/years_and_booksIDs.csv")

In [21]:
results.rename(columns={"book_id":"Etext Number"})

       year  Etext Number
0      1979         32771
1      1979         32772
2      1979         57347
3      1979         24582
4      1979         24586
...     ...           ...
32742  1759         38327
32743  1759         38444
32744  1759         39270
32745  1759         31339
32746  1990         52776

[32747 rows x 2 columns]

In [23]:
metadata_df_final = metadata_df.merge(results.rename(columns={"book_id":"Etext Number", "year":"Published Year"}), on="Etext Number")
metadata_df_final

,Etext Number,Title,Bookshelves,Authors,rights,Subjects,Published Year
0,1,The Declaration of Independence of the United ...,Politics; American Revolutionary War; United S...,"Jefferson, Thomas",Public domain in the USA.,E201 ; JK ; United States -- History -- Revolu...,1878
1,3,John F. Kennedy's Inaugural Address,Browsing: History - American; Browsing: Politics,"Kennedy, John F. (John Fitzgerald)",Public domain in the USA.,E838 ; United States -- Foreign relations -- 1...,1776
2,5,The United States Constitution,United States; Politics; American Revolutionar...,United States,Public domain in the USA.,JK ; United States. Constitution ; United Stat...,1776
3,6,Give Me Liberty or Give Me Death,American Revolutionary War; Browsing: History ...,"Henry, Patrick",Public domain in the USA.,E201 ; United States -- Politics and governmen...,1878
4,8,Abraham Lincoln's Second Inaugural Address,US Civil War; Browsing: History - American; Br...,"Lincoln, Abraham",Public domain in the USA.,E456 ; United States -- Politics and governmen...,1861
...,...,...,...,...,...,...,...
32742,75551,Reminiscences of the South Seas,NaN,"La Farge, John",Public domain in the USA.,NaN,1979
32743,75553,Among the camps,NaN,"Page, Thomas Nelson",Public domain in the USA.,NaN,1902
32744,75559,"The journal of George Fox, vol. 1 of 2",NaN,"Fox, George, 1624-1691; Fox, Margaret Askew Fe...",NaN,NaN,1789
32745,75561,Some old masters of Greek architecture,NaN,"Douglas, Harry, 1857-1938; Farrand, Charles D....",NaN,"Architecture, Greek; Architecture -- Greece",1979
32746,75563,"Cedar chests, how to make them",NaN,"Windoes, Ralph Flagg, 1891-1967",NaN,Chests,1979

In [ ]:
#metadata_df_final.to_csv("../data/metadata_with_years.csv")