In [9]:
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shutil
import os
import polars as pl
from tqdm.notebook import tqdm

In [10]:
##### ‼️⚠️ THIS CELL MIGHT TAKE AROUND 15 MIN TO LOAD THE ENTIRE METADATA IF IT IS YOUR FIRST TIME RUNNING IT ‼️⚠️
##### ‼️⚠️ IT DOWNLOADS THE DATASET IN YOUR CACHE AND MAY TAKE SOME SPACE ‼️⚠️
DOWNLOAD = False
if DOWNLOAD:
    path = kagglehub.dataset_download("lokeshparab/gutenberg-books-and-metadata-2025")
else:
    your_path = '/Users/eglantinevialaneix'
    path =  your_path + '/.cache/kagglehub/datasets/lokeshparab/gutenberg-books-and-metadata-2025/versions/4/'

print("Path to dataset files:", path)

Path to dataset files: /Users/eglantinevialaneix/.cache/kagglehub/datasets/lokeshparab/gutenberg-books-and-metadata-2025/versions/4/

In [11]:
total, used, free = shutil.disk_usage(os.path.expanduser("~/.cache/kagglehub"))
print(f"Total cache: {total / 1024**2:.2f} MB")
print(f"Cache used: {used / 1024**2:.2f} MB = {100 * used / total:.2f} %")
print(f"Free left: {free / 1024**2:.2f} MB = {100 * free / total:.2f} %")

Total cache: 471482.08 MB
Cache used: 297010.95 MB = 63.00 %
Free left: 174471.13 MB = 37.00 %

In [12]:
import os

total = 0
for dirpath, dirnames, filenames in os.walk(path):
    for f in filenames:
        fp = os.path.join(dirpath, f)
        total += os.path.getsize(fp)

print(f"Folder size: {total / 1024**3:.2f} GB")

Folder size: 28.86 GB

In [13]:
file_count = sum(len(files) for _, _, files in os.walk(path + "/books"))
print(f"Total number of books: {file_count}")

Total number of books: 75370

In [14]:
print(f"The csv file takes {os.path.getsize(path + "/gutenberg_metadata.csv") / 1024**2:.2f} MB of memory.")

The csv file takes 83.68 MB of memory.

In [7]:
df_raw = pd.read_csv(path + "/gutenberg_metadata.csv")
df_raw

,Etext Number,Type,Issued,Title,Language,LoCC,Bookshelves,Authors,rights,Subjects,...,EPUB3 (E-readers incl. Send-to-Kindle),EPUB (older E-readers),"EPUB (no images, older E-readers)",Kindle,Kindle (E-readers incl. Send-to-Kindle),"Kindle (no images, older E-readers)",Plain Text UTF-8,Download HTML(zip),Resource Description Framework (RDF),Other Links
0,1,Text,1971-12-01,The Declaration of Independence of the United ...,en,E201; JK,Politics; American Revolutionary War; United S...,"Jefferson, Thomas",Public domain in the USA.,E201 ; JK ; United States -- History -- Revolu...,...,https://www.gutenberg.org/ebooks/1.epub3.images,https://www.gutenberg.org/ebooks/1.epub.images,https://www.gutenberg.org/ebooks/1.epub.noimages,https://www.gutenberg.org/ebooks/1.kf8.images,https://www.gutenberg.org/ebooks/1.kindle.images,https://www.gutenberg.org/ebooks/1.kindle.noim...,https://www.gutenberg.org/ebooks/1.txt.utf-8,https://www.gutenberg.org/files/1/1-h.zip,https://www.gutenberg.org/ebooks/1.rdf,https://www.gutenberg.org/files/1/1-h/1-h.htm ...
1,2,Text,1972-12-01,The United States Bill of Rights\r\nThe Ten Or...,en,JK; KF,Politics; American Revolutionary War; United S...,United States,Public domain in the USA.,Civil rights -- United States -- Sources ; JK ...,...,https://www.gutenberg.org/ebooks/2.epub3.images,https://www.gutenberg.org/ebooks/2.epub.images,https://www.gutenberg.org/ebooks/2.epub.noimages,https://www.gutenberg.org/ebooks/2.kf8.images,https://www.gutenberg.org/ebooks/2.kindle.images,https://www.gutenberg.org/ebooks/2.kindle.noim...,https://www.gutenberg.org/ebooks/2.txt.utf-8,https://www.gutenberg.org/files/2/2-h.zip,https://www.gutenberg.org/ebooks/2.rdf,https://www.gutenberg.org/files/2/2-h/2-h.htm ...
2,3,Text,1973-11-01,John F. Kennedy's Inaugural Address,en,E838,Browsing: History - American; Browsing: Politics,"Kennedy, John F. (John Fitzgerald)",Public domain in the USA.,E838 ; United States -- Foreign relations -- 1...,...,https://www.gutenberg.org/ebooks/3.epub3.images,https://www.gutenberg.org/ebooks/3.epub.images,https://www.gutenberg.org/ebooks/3.epub.noimages,https://www.gutenberg.org/ebooks/3.kf8.images,https://www.gutenberg.org/ebooks/3.kindle.images,https://www.gutenberg.org/ebooks/3.kindle.noim...,https://www.gutenberg.org/ebooks/3.txt.utf-8,https://www.gutenberg.org/cache/epub/3/pg3-h.zip,https://www.gutenberg.org/ebooks/3.rdf,https://www.gutenberg.org/cache/epub/3/pg3.cov...
3,4,Text,1973-11-01,Lincoln's Gettysburg Address\r\nGiven November...,en,E456,US Civil War; Browsing: History - American; Br...,"Lincoln, Abraham",Public domain in the USA.,E456 ; Soldiers' National Cemetery (Gettysburg...,...,https://www.gutenberg.org/ebooks/4.epub3.images,https://www.gutenberg.org/ebooks/4.epub.images,https://www.gutenberg.org/ebooks/4.epub.noimages,https://www.gutenberg.org/ebooks/4.kf8.images,https://www.gutenberg.org/ebooks/4.kindle.images,https://www.gutenberg.org/ebooks/4.kindle.noim...,https://www.gutenberg.org/ebooks/4.txt.utf-8,https://www.gutenberg.org/cache/epub/4/pg4-h.zip,https://www.gutenberg.org/ebooks/4.rdf,https://www.gutenberg.org/files/4/4.zip ; http...
4,5,Text,1975-12-01,The United States Constitution,en,JK; KF,United States; Politics; American Revolutionar...,United States,Public domain in the USA.,JK ; United States. Constitution ; United Stat...,...,https://www.gutenberg.org/ebooks/5.epub3.images,https://www.gutenberg.org/ebooks/5.epub.images,https://www.gutenberg.org/ebooks/5.epub.noimages,https://www.gutenberg.org/ebooks/5.kf8.images,https://www.gutenberg.org/ebooks/5.kindle.images,https://www.gutenberg.org/ebooks/5.kindle.noim...,https://www.gutenberg.org/ebooks/5.txt.utf-8,https://www.gutenberg.org/files/5/5-h.zip,https://www.gutenberg.org/ebooks/5.rdf,https://www.gutenberg.org/files/5/5.txt ; http...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75389,75565,Text,2025-03-08,The man with a grouch,en,NaN,NaN,"Stacpoole, H. De Vere (Henry De Vere), 1863-1951",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75390,75566,Text,2025-03-08,Visibility—Zero,en,NaN,NaN,"Stearns, Myron M. (Myron Morris), 1884-1963",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75391,75567,Text,2025-03-09,Highland annals,en,NaN,NaN,"Dargan, Olive Tilford, 1869-1968",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75392,75568,Text,2025-03-09,Franz Schuberts Lebenslied,de,NaN,NaN,"Lux, Joseph Aug. (Joseph August), 1871-1947",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75393,75569,Text,2025-03-09,Als ich noch der Waldbauernbub war. 2. Band.,de,NaN,NaN,"Rosegger, Peter, 1843-1918",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
display(df_raw)

,Etext Number,Type,Issued,Title,Language,LoCC,Bookshelves,Authors,rights,Subjects,...,EPUB3 (E-readers incl. Send-to-Kindle),EPUB (older E-readers),"EPUB (no images, older E-readers)",Kindle,Kindle (E-readers incl. Send-to-Kindle),"Kindle (no images, older E-readers)",Plain Text UTF-8,Download HTML(zip),Resource Description Framework (RDF),Other Links
0,1,Text,1971-12-01,The Declaration of Independence of the United ...,en,E201; JK,Politics; American Revolutionary War; United S...,"Jefferson, Thomas",Public domain in the USA.,E201 ; JK ; United States -- History -- Revolu...,...,https://www.gutenberg.org/ebooks/1.epub3.images,https://www.gutenberg.org/ebooks/1.epub.images,https://www.gutenberg.org/ebooks/1.epub.noimages,https://www.gutenberg.org/ebooks/1.kf8.images,https://www.gutenberg.org/ebooks/1.kindle.images,https://www.gutenberg.org/ebooks/1.kindle.noim...,https://www.gutenberg.org/ebooks/1.txt.utf-8,https://www.gutenberg.org/files/1/1-h.zip,https://www.gutenberg.org/ebooks/1.rdf,https://www.gutenberg.org/files/1/1-h/1-h.htm ...
1,2,Text,1972-12-01,The United States Bill of Rights\r\nThe Ten Or...,en,JK; KF,Politics; American Revolutionary War; United S...,United States,Public domain in the USA.,Civil rights -- United States -- Sources ; JK ...,...,https://www.gutenberg.org/ebooks/2.epub3.images,https://www.gutenberg.org/ebooks/2.epub.images,https://www.gutenberg.org/ebooks/2.epub.noimages,https://www.gutenberg.org/ebooks/2.kf8.images,https://www.gutenberg.org/ebooks/2.kindle.images,https://www.gutenberg.org/ebooks/2.kindle.noim...,https://www.gutenberg.org/ebooks/2.txt.utf-8,https://www.gutenberg.org/files/2/2-h.zip,https://www.gutenberg.org/ebooks/2.rdf,https://www.gutenberg.org/files/2/2-h/2-h.htm ...
2,3,Text,1973-11-01,John F. Kennedy's Inaugural Address,en,E838,Browsing: History - American; Browsing: Politics,"Kennedy, John F. (John Fitzgerald)",Public domain in the USA.,E838 ; United States -- Foreign relations -- 1...,...,https://www.gutenberg.org/ebooks/3.epub3.images,https://www.gutenberg.org/ebooks/3.epub.images,https://www.gutenberg.org/ebooks/3.epub.noimages,https://www.gutenberg.org/ebooks/3.kf8.images,https://www.gutenberg.org/ebooks/3.kindle.images,https://www.gutenberg.org/ebooks/3.kindle.noim...,https://www.gutenberg.org/ebooks/3.txt.utf-8,https://www.gutenberg.org/cache/epub/3/pg3-h.zip,https://www.gutenberg.org/ebooks/3.rdf,https://www.gutenberg.org/cache/epub/3/pg3.cov...
3,4,Text,1973-11-01,Lincoln's Gettysburg Address\r\nGiven November...,en,E456,US Civil War; Browsing: History - American; Br...,"Lincoln, Abraham",Public domain in the USA.,E456 ; Soldiers' National Cemetery (Gettysburg...,...,https://www.gutenberg.org/ebooks/4.epub3.images,https://www.gutenberg.org/ebooks/4.epub.images,https://www.gutenberg.org/ebooks/4.epub.noimages,https://www.gutenberg.org/ebooks/4.kf8.images,https://www.gutenberg.org/ebooks/4.kindle.images,https://www.gutenberg.org/ebooks/4.kindle.noim...,https://www.gutenberg.org/ebooks/4.txt.utf-8,https://www.gutenberg.org/cache/epub/4/pg4-h.zip,https://www.gutenberg.org/ebooks/4.rdf,https://www.gutenberg.org/files/4/4.zip ; http...
4,5,Text,1975-12-01,The United States Constitution,en,JK; KF,United States; Politics; American Revolutionar...,United States,Public domain in the USA.,JK ; United States. Constitution ; United Stat...,...,https://www.gutenberg.org/ebooks/5.epub3.images,https://www.gutenberg.org/ebooks/5.epub.images,https://www.gutenberg.org/ebooks/5.epub.noimages,https://www.gutenberg.org/ebooks/5.kf8.images,https://www.gutenberg.org/ebooks/5.kindle.images,https://www.gutenberg.org/ebooks/5.kindle.noim...,https://www.gutenberg.org/ebooks/5.txt.utf-8,https://www.gutenberg.org/files/5/5-h.zip,https://www.gutenberg.org/ebooks/5.rdf,https://www.gutenberg.org/files/5/5.txt ; http...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75389,75565,Text,2025-03-08,The man with a grouch,en,NaN,NaN,"Stacpoole, H. De Vere (Henry De Vere), 1863-1951",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75390,75566,Text,2025-03-08,Visibility—Zero,en,NaN,NaN,"Stearns, Myron M. (Myron Morris), 1884-1963",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75391,75567,Text,2025-03-09,Highland annals,en,NaN,NaN,"Dargan, Olive Tilford, 1869-1968",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75392,75568,Text,2025-03-09,Franz Schuberts Lebenslied,de,NaN,NaN,"Lux, Joseph Aug. (Joseph August), 1871-1947",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75393,75569,Text,2025-03-09,Als ich noch der Waldbauernbub war. 2. Band.,de,NaN,NaN,"Rosegger, Peter, 1843-1918",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#TODO: filter all documents that contains the word opium
#TODO: count how many documetns and how many instances of the word
#TODO: see the genres and the distributionp of the topics (bookshelves)
#TODO: extract text snippets of the opium mentions

with open(path + '/books/7', 'r') as file:
    content = file.read()
    print(content)

The Project Gutenberg eBook of The Mayflower Compact

This eBook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this eBook or online at
www.gutenberg.org. If you are not located in the United States, you
will have to check the laws of the country where you are located before
using this eBook.

Title: The Mayflower Compact

Release Date: December 31, 1977 [eBook #7]
[Most recently updated: December 14, 2023]

Language: English


*** START OF THE PROJECT GUTENBERG EBOOK THE MAYFLOWER COMPACT ***




The Mayflower Compact

November 11, 1620  [This was November 21, old style calendar]

In the name of God, Amen.  We, whose names are underwritten, the Loyal
Subjects of our dread Sovereigne Lord, King James, by the Grace of God,
of Great Britaine, France, and Ireland, King, Defender of the Faith,
&c.

Having undertaken for the Glory of God, and Advancement of the
Christian Faith, and the Honour of our King and Country, a Voyage to
plant the first colony in the Northerne Parts of Virginia; doe, by
these Presents, solemnly and mutually in the Presence of God and one of
another, covenant and combine ourselves together into a civill Body
Politick, for our better Ordering and Preservation, and Furtherance of
the Ends aforesaid; And by Virtue hereof to enact, constitute, and
frame, such just and equall Laws, Ordinances, Acts, Constitutions, and
Offices, from time to time, as shall be thought most meete and
convenient for the Generall Good of the Colonie; unto which we promise
all due Submission and Obedience.

In Witness whereof we have hereunto subscribed our names at Cape Cod
the eleventh of November, in the Raigne of our Sovereigne Lord, King
James of England, France, and Ireland, the eighteenth, and of Scotland,
the fiftie-fourth, Anno. Domini, 1620.

Mr. John Carver           Mr. Stephen Hopkins
Mr. William Bradford      Digery Priest
Mr. Edward Winslow        Thomas Williams
Mr. William Brewster      Gilbert Winslow
Isaac Allerton            Edmund Margesson
Miles Standish            Peter Brown
John Alden                Richard Bitteridge
John Turner               George Soule
Francis Eaton             Edward Tilly
James Chilton             John Tilly
John Craxton              Francis Cooke
John Billington           Thomas Rogers
Joses Fletcher            Thomas Tinker
John Goodman              John Ridgate
Mr. Samuel Fuller         Edward Fuller
Mr. Christopher Martin    Richard Clark
Mr. William Mullins       Richard Gardiner
Mr. William White         Mr. John Allerton
Mr. Richard Warren        Thomas English
John Howland              Edward Doten
Edward Liester




*** END OF THE PROJECT GUTENBERG EBOOK THE MAYFLOWER COMPACT ***

Updated editions will replace the previous one--the old editions will
be renamed.

Creating the works from print editions not protected by U.S. copyright
law means that no one owns a United States copyright in these works,
so the Foundation (and you!) can copy and distribute it in the
United States without permission and without paying copyright
royalties. Special rules, set forth in the General Terms of Use part
of this license, apply to copying and distributing Project
Gutenberg™ electronic works to protect the PROJECT GUTENBERG™
concept and trademark. Project Gutenberg is a registered trademark,
and may not be used if you charge for an eBook, except by following
the terms of the trademark license, including paying royalties for use
of the Project Gutenberg trademark. If you do not charge anything for
copies of this eBook, complying with the trademark license is very
easy. You may use this eBook for nearly any purpose such as creation
of derivative works, reports, performances and research. Project
Gutenberg eBooks may be modified and printed and given away--you may
do practically ANYTHING in the United States with eBooks not protected
by U.S. copyright law. Redistribution is subject to the trademark
license, especially commercial redistribution.

START: FULL LICENSE

THE FULL PROJECT GUTENBERG LICENSE
PLEASE READ THIS BEFORE YOU DISTRIBUTE OR USE THIS WORK

To protect the Project Gutenberg™ mission of promoting the free
distribution of electronic works, by using or distributing this work
(or any other work associated in any way with the phrase “Project
Gutenberg”), you agree to comply with all the terms of the Full
Project Gutenberg™ License available with this file or online at
www.gutenberg.org/license.

Section 1. General Terms of Use and Redistributing Project
Gutenberg™ electronic works

1.A. By reading or using any part of this Project Gutenberg™
electronic work, you indicate that you have read, understand, agree to
and accept all the terms of this license and intellectual property
(trademark/copyright) agreement. If you do not agree to abide by all
the terms of this agreement, you must cease using and return or
destroy all copies of Project Gutenberg™ electronic works in your
possession. If you paid a fee for obtaining a copy of or access to a
Project Gutenberg™ electronic work and you do not agree to be bound
by the terms of this agreement, you may obtain a refund from the
person or entity to whom you paid the fee as set forth in paragraph
1.E.8.

1.B. “Project Gutenberg” is a registered trademark. It may only be
used on or associated in any way with an electronic work by people who
agree to be bound by the terms of this agreement. There are a few
things that you can do with most Project Gutenberg™ electronic works
even without complying with the full terms of this agreement. See
paragraph 1.C below. There are a lot of things you can do with Project
Gutenberg™ electronic works if you follow the terms of this
agreement and help preserve free future access to Project Gutenberg™
electronic works. See paragraph 1.E below.

1.C. The Project Gutenberg Literary Archive Foundation (“the
Foundation” or PGLAF), owns a compilation copyright in the collection
of Project Gutenberg™ electronic works. Nearly all the individual
works in the collection are in the public domain in the United
States. If an individual work is unprotected by copyright law in the
United States and you are located in the United States, we do not
claim a right to prevent you from copying, distributing, performing,
displaying or creating derivative works based on the work as long as
all references to Project Gutenberg are removed. Of course, we hope
that you will support the Project Gutenberg™ mission of promoting
free access to electronic works by freely sharing Project Gutenberg™
works in compliance with the terms of this agreement for keeping the
Project Gutenberg™ name associated with the work. You can easily
comply with the terms of this agreement by keeping this work in the
same format with its attached full Project Gutenberg™ License when
you share it without charge with others.

1.D. The copyright laws of the place where you are located also govern
what you can do with this work. Copyright laws in most countries are
in a constant state of change. If you are outside the United States,
check the laws of your country in addition to the terms of this
agreement before downloading, copying, displaying, performing,
distributing or creating derivative works based on this work or any
other Project Gutenberg™ work. The Foundation makes no
representations concerning the copyright status of any work in any
country other than the United States.

1.E. Unless you have removed all references to Project Gutenberg:

1.E.1. The following sentence, with active links to, or other
immediate access to, the full Project Gutenberg™ License must appear
prominently whenever any copy of a Project Gutenberg™ work (any work
on which the phrase “Project Gutenberg” appears, or with which the
phrase “Project Gutenberg” is associated) is accessed, displayed,
performed, viewed, copied or distributed:

  This eBook is for the use of anyone anywhere in the United States and
  most other parts of the world at no cost and with almost no
  restrictions whatsoever. You may copy it, give it away or re-use it
  under the terms of the Project Gutenberg License included with this
  eBook or online at www.gutenberg.org. If you are not located in the
  United States, you will have to check the laws of the country where
  you are located before using this eBook.

1.E.2. If an individual Project Gutenberg™ electronic work is
derived from texts not protected by U.S. copyright law (does not
contain a notice indicating that it is posted with permission of the
copyright holder), the work can be copied and distributed to anyone in
the United States without paying any fees or charges. If you are
redistributing or providing access to a work with the phrase “Project
Gutenberg” associated with or appearing on the work, you must comply
either with the requirements of paragraphs 1.E.1 through 1.E.7 or
obtain permission for the use of the work and the Project Gutenberg™
trademark as set forth in paragraphs 1.E.8 or 1.E.9.

1.E.3. If an individual Project Gutenberg™ electronic work is posted
with the permission of the copyright holder, your use and distribution
must comply with both paragraphs 1.E.1 through 1.E.7 and any
additional terms imposed by the copyright holder. Additional terms
will be linked to the Project Gutenberg™ License for all works
posted with the permission of the copyright holder found at the
beginning of this work.

1.E.4. Do not unlink or detach or remove the full Project Gutenberg™
License terms from this work, or any files containing a part of this
work or any other work associated with Project Gutenberg™.

1.E.5. Do not copy, display, perform, distribute or redistribute this
electronic work, or any part of this electronic work, without
prominently displaying the sentence set forth in paragraph 1.E.1 with
active links or immediate access to the full terms of the Project
Gutenberg™ License.

1.E.6. You may convert to and distribute this work in any binary,
compressed, marked up, nonproprietary or proprietary form, including
any word processing or hypertext form. However, if you provide access
to or distribute copies of a Project Gutenberg™ work in a format
other than “Plain Vanilla ASCII” or other format used in the official
version posted on the official Project Gutenberg™ website
(www.gutenberg.org), you must, at no additional cost, fee or expense
to the user, provide a copy, a means of exporting a copy, or a means
of obtaining a copy upon request, of the work in its original “Plain
Vanilla ASCII” or other form. Any alternate format must include the
full Project Gutenberg™ License as specified in paragraph 1.E.1.

1.E.7. Do not charge a fee for access to, viewing, displaying,
performing, copying or distributing any Project Gutenberg™ works
unless you comply with paragraph 1.E.8 or 1.E.9.

1.E.8. You may charge a reasonable fee for copies of or providing
access to or distributing Project Gutenberg™ electronic works
provided that:

• You pay a royalty fee of 20% of the gross profits you derive from
  the use of Project Gutenberg™ works calculated using the method
  you already use to calculate your applicable taxes. The fee is owed
  to the owner of the Project Gutenberg™ trademark, but he has
  agreed to donate royalties under this paragraph to the Project
  Gutenberg Literary Archive Foundation. Royalty payments must be paid
  within 60 days following each date on which you prepare (or are
  legally required to prepare) your periodic tax returns. Royalty
  payments should be clearly marked as such and sent to the Project
  Gutenberg Literary Archive Foundation at the address specified in
  Section 4, “Information about donations to the Project Gutenberg
  Literary Archive Foundation.”

• You provide a full refund of any money paid by a user who notifies
  you in writing (or by e-mail) within 30 days of receipt that s/he
  does not agree to the terms of the full Project Gutenberg™
  License. You must require such a user to return or destroy all
  copies of the works possessed in a physical medium and discontinue
  all use of and all access to other copies of Project Gutenberg™
  works.

• You provide, in accordance with paragraph 1.F.3, a full refund of
  any money paid for a work or a replacement copy, if a defect in the
  electronic work is discovered and reported to you within 90 days of
  receipt of the work.

• You comply with all other terms of this agreement for free
  distribution of Project Gutenberg™ works.

1.E.9. If you wish to charge a fee or distribute a Project
Gutenberg™ electronic work or group of works on different terms than
are set forth in this agreement, you must obtain permission in writing
from the Project Gutenberg Literary Archive Foundation, the manager of
the Project Gutenberg™ trademark. Contact the Foundation as set
forth in Section 3 below.

1.F.

1.F.1. Project Gutenberg volunteers and employees expend considerable
effort to identify, do copyright research on, transcribe and proofread
works not protected by U.S. copyright law in creating the Project
Gutenberg™ collection. Despite these efforts, Project Gutenberg™
electronic works, and the medium on which they may be stored, may
contain “Defects,” such as, but not limited to, incomplete, inaccurate
or corrupt data, transcription errors, a copyright or other
intellectual property infringement, a defective or damaged disk or
other medium, a computer virus, or computer codes that damage or
cannot be read by your equipment.

1.F.2. LIMITED WARRANTY, DISCLAIMER OF DAMAGES - Except for the “Right
of Replacement or Refund” described in paragraph 1.F.3, the Project
Gutenberg Literary Archive Foundation, the owner of the Project
Gutenberg™ trademark, and any other party distributing a Project
Gutenberg™ electronic work under this agreement, disclaim all
liability to you for damages, costs and expenses, including legal
fees. YOU AGREE THAT YOU HAVE NO REMEDIES FOR NEGLIGENCE, STRICT
LIABILITY, BREACH OF WARRANTY OR BREACH OF CONTRACT EXCEPT THOSE
PROVIDED IN PARAGRAPH 1.F.3. YOU AGREE THAT THE FOUNDATION, THE
TRADEMARK OWNER, AND ANY DISTRIBUTOR UNDER THIS AGREEMENT WILL NOT BE
LIABLE TO YOU FOR ACTUAL, DIRECT, INDIRECT, CONSEQUENTIAL, PUNITIVE OR
INCIDENTAL DAMAGES EVEN IF YOU GIVE NOTICE OF THE POSSIBILITY OF SUCH
DAMAGE.

1.F.3. LIMITED RIGHT OF REPLACEMENT OR REFUND - If you discover a
defect in this electronic work within 90 days of receiving it, you can
receive a refund of the money (if any) you paid for it by sending a
written explanation to the person you received the work from. If you
received the work on a physical medium, you must return the medium
with your written explanation. The person or entity that provided you
with the defective work may elect to provide a replacement copy in
lieu of a refund. If you received the work electronically, the person
or entity providing it to you may choose to give you a second
opportunity to receive the work electronically in lieu of a refund. If
the second copy is also defective, you may demand a refund in writing
without further opportunities to fix the problem.

1.F.4. Except for the limited right of replacement or refund set forth
in paragraph 1.F.3, this work is provided to you ‘AS-IS’, WITH NO
OTHER WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PURPOSE.

1.F.5. Some states do not allow disclaimers of certain implied
warranties or the exclusion or limitation of certain types of
damages. If any disclaimer or limitation set forth in this agreement
violates the law of the state applicable to this agreement, the
agreement shall be interpreted to make the maximum disclaimer or
limitation permitted by the applicable state law. The invalidity or
unenforceability of any provision of this agreement shall not void the
remaining provisions.

1.F.6. INDEMNITY - You agree to indemnify and hold the Foundation, the
trademark owner, any agent or employee of the Foundation, anyone
providing copies of Project Gutenberg™ electronic works in
accordance with this agreement, and any volunteers associated with the
production, promotion and distribution of Project Gutenberg™
electronic works, harmless from all liability, costs and expenses,
including legal fees, that arise directly or indirectly from any of
the following which you do or cause to occur: (a) distribution of this
or any Project Gutenberg™ work, (b) alteration, modification, or
additions or deletions to any Project Gutenberg™ work, and (c) any
Defect you cause.

Section 2. Information about the Mission of Project Gutenberg™

Project Gutenberg™ is synonymous with the free distribution of
electronic works in formats readable by the widest variety of
computers including obsolete, old, middle-aged and new computers. It
exists because of the efforts of hundreds of volunteers and donations
from people in all walks of life.

Volunteers and financial support to provide volunteers with the
assistance they need are critical to reaching Project Gutenberg™'s
goals and ensuring that the Project Gutenberg™ collection will
remain freely available for generations to come. In 2001, the Project
Gutenberg Literary Archive Foundation was created to provide a secure
and permanent future for Project Gutenberg™ and future
generations. To learn more about the Project Gutenberg Literary
Archive Foundation and how your efforts and donations can help, see
Sections 3 and 4 and the Foundation information page at
www.gutenberg.org.

Section 3. Information about the Project Gutenberg Literary
Archive Foundation

The Project Gutenberg Literary Archive Foundation is a non-profit
501(c)(3) educational corporation organized under the laws of the
state of Mississippi and granted tax exempt status by the Internal
Revenue Service. The Foundation’s EIN or federal tax identification
number is 64-6221541. Contributions to the Project Gutenberg Literary
Archive Foundation are tax deductible to the full extent permitted by
U.S. federal laws and your state's laws.

The Foundation’s business office is located at 809 North 1500 West,
Salt Lake City, UT 84116, (801) 596-1887. Email contact links and up
to date contact information can be found at the Foundation’s website
and official page at www.gutenberg.org/contact.

Section 4. Information about Donations to the Project Gutenberg
Literary Archive Foundation

Project Gutenberg™ depends upon and cannot survive without
widespread public support and donations to carry out its mission of
increasing the number of public domain and licensed works that can be
freely distributed in machine-readable form accessible by the widest
array of equipment including outdated equipment. Many small donations
($1 to $5,000) are particularly important to maintaining tax exempt
status with the IRS.

The Foundation is committed to complying with the laws regulating
charities and charitable donations in all 50 states of the United
States. Compliance requirements are not uniform and it takes a
considerable effort, much paperwork and many fees to meet and keep up
with these requirements. We do not solicit donations in locations
where we have not received written confirmation of compliance. To SEND
DONATIONS or determine the status of compliance for any particular
state visit www.gutenberg.org/donate.

While we cannot and do not solicit contributions from states where we
have not met the solicitation requirements, we know of no prohibition
against accepting unsolicited donations from donors in such states who
approach us with offers to donate.

International donations are gratefully accepted, but we cannot make
any statements concerning tax treatment of donations received from
outside the United States. U.S. laws alone swamp our small staff.

Please check the Project Gutenberg web pages for current donation

In [11]:
opium_filenames = []
for dirpath, dirnames, filenames in os.walk(path + "/books"):
    for fn in filenames:
        full_path = os.path.join(dirpath, fn)
        with open(full_path) as f:
            if 'opium' in f.read():
                opium_filenames.append(fn)
            
opium_filenames

['72882',
 '56019',
 '21977',
 '59051',
 '2886',
 '28690',
 '8580',
 '32138',
 '5891',
 '135',
 '43369',
 '48781',
 '70379',
 '52029',
 '75439',
 '66812',
 '68988',
 '5059',
 '307',
 '69402',
 '31923',
 '72876',
 '7964',
 '69630',
 '20851',
 '65660',
 '23075',
 '47530',
 '12732',
 '1432',
 '70180',
 '68943',
 '11385',
 '45055',
 '35322',
 '47702',
 '49698',
 '4716',
 '37011',
 '51203',
 '3701',
 '20294',
 '38891',
 '67795',
 '2415',
 '72849',
 '16366',
 '22153',
 '23081',
 '30496',
 '13614',
 '57756',
 '41633',
 '14431',
 '63751',
 '72411',
 '12994',
 '53598',
 '14851',
 '74188',
 '59290',
 '61668',
 '62489',
 '14409',
 '55039',
 '49654',
 '48786',
 '33019',
 '25940',
 '45099',
 '3953',
 '8587',
 '9455',
 '1638',
 '45851',
 '65832',
 '56822',
 '38253',
 '11376',
 '46623',
 '2076',
 '25371',
 '41634',
 '66016',
 '49801',
 '69608',
 '39944',
 '67792',
 '43735',
 '569',
 '27270',
 '17623',
 '71431',
 '14294',
 '57597',
 '44180',
 '47705',
 '50580',
 '67130',
 '53305',
 '37640',
 '34038',
 '25378',
 '70946',
 '25976',
 '2843',
 '61834',
 '8545',
 '39171',
 '49206',
 '27279',
 '14867',
 '39343',
 '56028',
 '48320',
 '27883',
 '48112',
 '38265',
 '21348',
 '54129',
 '4972',
 '71860',
 '63599',
 '10857',
 '53902',
 '24850',
 '5433',
 '31111',
 '55454',
 '64121',
 '41054',
 '44526',
 '16165',
 '2040',
 '68388',
 '70377',
 '71097',
 '37682',
 '28458',
 '73506',
 '1403',
 '45256',
 '18239',
 '41292',
 '54740',
 '53565',
 '60129',
 '9464',
 '29546',
 '9656',
 '35925',
 '68176',
 '38606',
 '11982',
 '48929',
 '51804',
 '62814',
 '26358',
 '19585',
 '6874',
 '54778',
 '48327',
 '69606',
 '567',
 '6880',
 '58525',
 '103',
 '55008',
 '66824',
 '65000',
 '75292',
 '20090',
 '37215',
 '53750',
 '12360',
 '29921',
 '10053',
 '68975',
 '65464',
 '43394',
 '56474',
 '25340',
 '5050',
 '13622',
 '19916',
 '48788',
 '56480',
 '73191',
 '13848',
 '61454',
 '26393',
 '43704',
 '2423',
 '57136',
 '63303',
 '57304',
 '5434',
 '67591',
 '20256',
 '17646',
 '74126',
 '25784',
 '38807',
 '30256',
 '54713',
 '1662',
 '12562',
 '47760',
 '60370',
 '53360',
 '75490',
 '21586',
 '41463',
 '63733',
 '1696',
 '13444',
 '55251',
 '61858',
 '13676',
 '50511',
 '72641',
 '46474',
 '41651',
 '38699',
 '40783',
 '29981',
 '44747',
 '63959',
 '66417',
 '11545',
 '39921',
 '4780',
 '24490',
 '38652',
 '27488',
 '6478',
 '47935',
 '72028',
 '14008',
 '31941',
 '365',
 '61269',
 '55860',
 '8516',
 '5209',
 '71695',
 '25545',
 '42685',
 '55632',
 '29986',
 '27020',
 '72222',
 '65295',
 '28068',
 '2226',
 '43101',
 '13671',
 '55064',
 '22136',
 '16303',
 '70111',
 '33044',
 '13443',
 '27676',
 '50724',
 '3300',
 '56615',
 '4919',
 '21575',
 '53155',
 '14692',
 '41490',
 '38458',
 '54370',
 '12565',
 '73552',
 '47767',
 '59837',
 '6818',
 '23646',
 '65261',
 '47131',
 '70581',
 '18094',
 '19146',
 '66877',
 '63961',
 '30894',
 '72813',
 '13018',
 '43768',
 '20008',
 '70778',
 '37883',
 '2689',
 '9261',
 '50985',
 '54519',
 '65850',
 '68317',
 '10803',
 '68919',
 '41660',
 '25325',
 '61267',
 '13647',
 '60187',
 '7550',
 '34257',
 '13011',
 '43761',
 '63968',
 '20233',
 '43553',
 '7306',
 '72214',
 '49855',
 '16751',
 '43795',
 '51250',
 '70785',
 '5697',
 '74325',
 '37270',
 '38238',
 '31187',
 '64385',
 '45234',
 '56623',
 '51634',
 '19987',
 '6476',
 '47751',
 '730',
 '23489',
 '62885',
 '69663',
 '41009',
 '5238',
 '21588',
 '1698',
 '61856',
 '19342',
 '61258',
 '22903',
 '20668',
 '39745',
 '10835',
 '67967',
 '17648',
 '56876',
 '73903',
 '3103',
 '29729',
 '73563',
 '33081',
 '62623',
 '67163',
 '10031',
 '27481',
 '30436',
 '35144',
 '18638',
 '28891',
 '29943',
 '64382',
 '3567',
 '10667',
 '71496',
 '52614',
 '20234',
 '33623',
 '43554',
 '2673',
 '48980',
 '64376',
 '3593',
 '70776',
 '10693',
 '19148',
 '43302',
 '44127',
 '63705',
 '33075',
 '59698',
 '55869',
 '64712',
 '54528',
 '47903',
 '49899',
 '54970',
 '59653',
 '38664',
 '38456',
 '53967',
 '29716',
 '3900',
 '6688',
 '38690',
 '39928',
 '24499',
 '9096',
 '43759',
 '505',
 '72822',
 '49263',
 '48183',
 '34439',
 '64349',
 '69607',
 '6881',
 '46846',
 '3399',
 '19326',
 '55009',
 '71892',
 '39721',
 '4148',
 '10851',
 '4974',
 '38607',
 '59402',
 '71268',
 '25984',
 '30658',
 '18032',
 '3963',
 '40977',
 '58988',
 '19584',
 '54779',
 '48928',
 '1862',
 '62029',
 '30693',
 '16163',
 '57553',
 '14406',
 '13623',
 '11510',
 '8118',
 '8924',
 '28208',
 '70715',
 '59891',
 '69638',
 '71401',
 '18469',
 '73164',
 '37026',
 '15376',
 '10604',
 '1637',
 '11180',
 '5899',
 '68148',
 '30455',
 '73732',
 '29918',
 '46089',
 '75099',
 '3964',
 '42871',
 '4973',
 '58523',
 '39514',
 '42885',
 '58711',
 '18697',
 '6886',
 '561',
 '15527',
 '50785',
 '45065',
 '12968',
 '47356',
 '39987',
 '14091',
 '15143',
 '71406',
 '45633',
 '24604',
 '3731',
 '798',
 '55667',
 '64120',
 '14257',
 '44527',
 '5600',
 '41055',
 '59298',
 '63137',
 '61660',
 '13240',
 '37683',
 '39719',
 '7701',
 '51491',
 '43366',
 '50771',
 '65496',
 '52026',
 '12539',
 '3952',
 '28696',
 '32902',
 '59433',
 '53935',
 '44982',
 '74519',
 '69094',
 '29576',
 '10438',
 '18467',
 '26368',
 '67758',
 '21971',
 '59291',
 '69404',
 '49003',
 '60589',
 '53599',
 '133',
 '24893',
 '52813',
 '39522',
 '70971',
 '66814',
 '14295',
 '48328',
 '32757',
 '26501',
 '43196',
 '70186',
 '5094',
 '1434',
 '45053',
 '1606',
 '12506',
 '65692',
 '41635',
 '37487',
 '4380',
 '13420',
 '2077',
 '75256',
 '568',
 '2413',
 '64116',
 '46246',
 '46848',
 '55463',
 '66473',
 '53794',
 '71098',
 '66813',
 '49460',
 '16358',
 '46428',
 '59296',
 '63905',
 '46870',
 '59050',
 '71408',
 '74946',
 '796',
 '68141',
 '8581',
 '29743',
 '43501',
 '16703',
 '70511',
 '44724',
 '40384',
 '70723',
 '31313',
 '7166',
 '37480',
 '41400',
 '9498',
 '16155',
 '13615',
 '34037',
 '23080',
 '41632',
 '53131',
 '71261',
 '57591',
 '23074',
 '50586',
 '17241',
 '15516',
 '1433',
 '42427',
 '26162',
 '47155',
 '35575',
 '53767',
 '67552',
 '37222',
 '40370',
 '45430',
 '74377',
 '40142',
 '30235',
 '3532',
 '12959',
 '9894',
 '8946',
 '13017',
 '55602',
 '25575',
 '11572',
 '70545',
 '37282',
 '5033',
 '14464',
 '36734',
 '13641',
 '6484',
 '57531',
 '63704',
 '44126',
 '36506',
 '15784',
 '52043',
 '74575',
 '61295',
 '60347',
 '27480',
 '51632',
 '37878',
 '57393',
 '73334',
 '18639',
 '8521',
 '16902',
 '55259',
 '54985',
 '34860',
 '5830',
 '67995',
 '41659',
 '58774',
 '16768',
 '51893',
 '14803',
 '24498',
 '52418',
 '21922',
 '40129',
 '59004',
 '38457',
 '39585',
 '52088',
 '12758',
 '56246',
 '10453',
 '22591',
 '28299',
 '54723',
 '25586',
 '4744',
 '6477',
 '54347',
 '1652',
 '62625',
 '67959',
 '71000',
 '73757',
 '63969',
 '37285',
 '13222',
 '46212',
 '48388',
 '13010',
 '10695',
 '57152',
 '58926',
 '70770',
 '72488',
 '38808',
 '9858',
 '48343',
 '73902',
 '65867',
 '1807',
 '55850',
 '54982',
 '355',
 '38696',
 '66840',
 '39576',
 '21589',
 '46649',
 '47766',
 '60144',
 '54143',
 '65260',
 '73305',
 '23475',
 '42442',
 '24650',
 '53702',
 '37247',
 '71452',
 '15117',
 '1200',
 '62277',
 '46016',
 '13214',
 '738',
 '2643',
 '44741',
 '75234',
 '37081',
 '14203',
 '57500',
 '36537',
 '5230',
 '6687',
 '2227',
 '36705',
 '20660',
 '44325',
 '8180',
 '18405',
 '10668',
 '68772',
 '57993',
 '18637',
 '2688',
 '68124',
 '68918',
 '18253',
 '12769',
 '3930',
 '29726',
 '17815',
 '56419',
 '53957',
 '11118',
 '54188',
 '52871',
 '69230',
 '38492',
 '58577',
 '7900',
 '64977',
 '39124',
 '56089',
 '71499',
 '29184',
 '40782',
 '5005',
 '20667',
 '21587',
 '50722',
 '33426',
 '63356',
 '24491',
 '71693',
 '51294',
 '34603',
 '17481',
 '50346',
 '10496',
 '33614',
 '14036',
 '45694',
 '62270',
 '71667',
 '51260',
 '23640',
 '12335',
 '56277',
 '21325',
 '4547',
 '46481',
 '26564',
 '56613',
 '40776',
 '45204',
 '24001',
 '45036',
 '53153',
 '61091',
 '8173',
 '72815',
 '58114',
 '16934',
 '70128',
 '43904',
 '49402',
 '68123',
 '73759',
 '19386',
 '56248',
 '59200',
 '30866',
 '16598',
 '8187',
 '64984',
 '1238',
 '21128',
 '12278',
 '59140',
 '41983',
 '74258',
 '9543',
 '28781',
 '67019',
 '37769',
 '67825',
 '19032',
 '39435',
 '25258',
 '75528',
 '8657',
 '39263',
 '54499',
 '22419',
 '44439',
 '69721',
 '12623',
 '47421',
 '50496',
 '45376',
 '4051',
 '67026',
 '4263',
 '12411',
 '14382',
 '15250',
 '40052',
 '41180',
 '56137',
 '7082',
 '3610',
 '6362',
 '40260',
 '20143',
 '21091',
 '63224',
 '11604',
 '31203',
 '13153',
 '34771',
 '61741',
 '18789',
 '28920',
 '66564',
 '43075',
 '41722',
 '75517',
 '44062',
 '14712',
 '2160',
 '7412',
 '72500',
 '75379',
 '70439',
 '28918',
 '43429',
 '62598',
 '49577',
 '61913',
 '25851',
 '41528',
 '74409',
 '65749',
 '32812',
 '1729',
 '65923',
 '54658',
 '37138',
 '1943',
 '62108',
 '48035',
 '37597',
 '27705',
 '820',
 '22879',
 '50465',
 '46500',
 '66107',
 '58608',
 '41725',
 '26081',
 '13366',
 '27153',
 '70406',
 '75174',
 '11431',
 '25604',
 '58862',
 '13968',
 '55587',
 '53670',
 '15065',
 '71712',
 '65120',
 '6157',
 '4264',
 '18910',
 '35234',
 '54031',
 '12624',
 '23163',
 '51543',
 '36683',
 '62553',
 '42995',
 '26088',
 '27966',
 '56905',
 '4609',
 '52599',
 '56139',
 '51912',
 '75189',
 '26418',
 '18317',
 '6708',
 '68060',
 '59388',
 '1182',
 '64202',
 '72155',
 '15295',
 '2151',
 '72531',
 '33101',
 '10383',
 '44261',
 '36641',
 '69179',
 '43044',
 '35202',
 '44295',
 '71172',
 '74400',
 '17360',
 '64692',
 '6737',
 '10521',
 '47074',
 '35454',
 '51111',
 '40063',
 '24946',
 '48004',
 '48838',
 '29033',
 '37109',
 '48236',
 '13368',
 '43418',
 '19652',
 '39255',
 '69717',
 '37599',
 '8453',
 '43840',
 '13191',
 '73848',
 '12043',
 '46393',
 '65111',
 '40256',
 '19699',
 '45340',
 '4067',
 '31497',
 '35037',
 '17367',
 '35205',
 '36480',
 '71347',
 '63444',
 '19209',
 '61313',
 '46531',
 '48699',
 '2156',
 '36474',
 '449',
 '13959',
 '39864',
 '5525',
 '11400',
 '57215',
 '28916',
 '2700',
 '6300',
 '60605',
 '3672',
 '42555',
 '56969',
 '30347',
 ...]

In [12]:
len(opium_filenames)

6528

# Chronoberg - joining the years on the metadata csv file

In [6]:
path_to_enormous_jsonl = "../../../../Downloads/history/ChronobergDataset.jsonl"

In [14]:
print(f"This file takes {os.path.getsize(path_to_enormous_jsonl) / 1e9:.2f} GB of memory.")

This file takes 10.40 GB of memory.

In [7]:
df = pl.read_ndjson(path_to_enormous_jsonl)
df.head()

shape: (5, 2)
┌──────┬────────────────────────────┐
│ year ┆ text                       │
│ ---  ┆ ---                        │
│ i64  ┆ str                        │
╞══════╪════════════════════════════╡
│ 1979 ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆ Transcriber's note:        │
│      ┆                            │
│      ┆ Exten…                     │
│ 1753 ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆                LETTERS TO… │
│ 1789 ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆ Persuasion                 │
│      ┆                            │
│      ┆                            │
│      ┆ by Jane Auste…             │
│ 1779 ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆ THE WRITINGS OF THOMAS PA… │
│ 1844 ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆                            │
│      ┆ THE LIFE OF FRANCIS MARIO… │
└──────┴────────────────────────────┘

In [16]:
df.shape

(249, 2)

In [17]:
df.item(0, 0)

1979

In [18]:
len(df.item(0, 1))

893053

In [19]:
# Takes 5 min approximately
WRITE_DF_IN_TXT_BY_YEAR = False
path_to_write = "../../../Downloads/history/years/"

if WRITE_DF_IN_TXT_BY_YEAR:
    for row in df.iter_rows():
        with open(f"{path_to_write}{row[0]}.txt", "w") as file:
            file.write(row[1])

In [20]:
all_titles = df_raw.Title.values
all_titles

<StringArray>
[                                              'The Declaration of Independence of the United States of America',
      'The United States Bill of Rights\r\nThe Ten Original Amendments to the Constitution of the United States',
                                                                           'John F. Kennedy's Inaugural Address',
 'Lincoln's Gettysburg Address\r\nGiven November 19, 1863 on the battlefield near Gettysburg, Pennsylvania, USA',
                                                                                'The United States Constitution',
                                                                              'Give Me Liberty or Give Me Death',
                                                                                         'The Mayflower Compact',
                                                                    'Abraham Lincoln's Second Inaugural Address',
                                                                     'Abraham Lincoln's First Inaugural Address',
                                                                           'The King James Version of the Bible',
 ...
                                                                                         'A-B-C of housekeeping',
                                                                        'Some old masters of Greek architecture',
                                                                                'The Assassination Bureau, Ltd.',
                                                                                'Cedar chests, how to make them',
                                                                                            'The puzzle of life',
                                                                                         'The man with a grouch',
                                                                                               'Visibility—Zero',
                                                                                               'Highland annals',
                                                                                    'Franz Schuberts Lebenslied',
                                                                  'Als ich noch der Waldbauernbub war. 2. Band.']
Length: 75394, dtype: str

In [22]:
import ahocorasick

time_span = np.arange(1856, 1920)
#sub_df = df.filter(pl.col("year").is_in(time_span))
sub_df = df.clone() #filter(pl.col("year").is_in(time_span))


# Build automaton once
A = ahocorasick.Automaton()
for title in all_titles:
    A.add_word(title, title)
A.make_automaton()

published_year = {title: [] for title in all_titles}
for year, text in tqdm(sub_df.iter_rows(), total=len(sub_df)):
    for _, title in A.iter(text):
        published_year[title].append(year)

  0%|          | 0/249 [00:00<?, ?it/s]

In [23]:
published_year

{'The Declaration of Independence of the United States of America': [],
 'The United States Bill of Rights\r\nThe Ten Original Amendments to the Constitution of the United States': [],
 "John F. Kennedy's Inaugural Address": [],
 "Lincoln's Gettysburg Address\r\nGiven November 19, 1863 on the battlefield near Gettysburg, Pennsylvania, USA": [],
 'The United States Constitution': [1889, 1920, 1913, 1905, 1890, 1961, 1922],
 'Give Me Liberty or Give Me Death': [1901, 1922],
 'The Mayflower Compact': [1889,
  1940,
  1929,
  1900,
  1900,
  1915,
  1915,
  1949,
  1922],
 "Abraham Lincoln's Second Inaugural Address": [],
 "Abraham Lincoln's First Inaugural Address": [],
 'The King James Version of the Bible': [],
 "Alice's Adventures in Wonderland": [1903,
  1903,
  1937,
  1889,
  1896,
  1896,
  1896,
  1902,
  1902,
  1906,
  1894,
  1907,
  1897,
  1897,
  1897,
  1897,
  1872,
  1872,
  1899,
  1899,
  1891,
  1874,
  1874,
  1865,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1921,
  1921,
  1920,
  1870,
  1900,
  1900,
  1916,
  1916,
  1895,
  1895,
  1895,
  1915,
  1893,
  1910,
  1892,
  1892,
  1892,
  1898,
  1898,
  1898,
  1898,
  1881,
  1890,
  1890,
  1890,
  1890,
  1876],
 'Through the Looking-Glass': [1903,
  1937,
  1882,
  1927,
  1906,
  1906,
  1906,
  1906,
  1906,
  1887,
  1887,
  1911,
  1911,
  1909,
  1909,
  1884,
  1907,
  1907,
  1897,
  1897,
  1899,
  1899,
  1899,
  1899,
  1899,
  1899,
  1960,
  1946,
  1914,
  1914,
  1921,
  1918,
  1920,
  1905,
  1915,
  1915,
  1893,
  1893,
  1893,
  1893,
  1910,
  1912,
  1904,
  1904,
  1904,
  1892,
  1898,
  1898,
  1898,
  1898,
  1898,
  1898,
  1881,
  1901,
  1864,
  1890,
  1890,
  1890,
  1876,
  1917,
  1917,
  1922,
  1922],
 'The Hunting of the Snark: An Agony in Eight Fits': [1896, 1895],
 'The 1990 CIA World Factbook': [],
 'Moby-Dick; or, The Whale': [],
 'Peter Pan': [1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1926,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1937,
  1937,
  1937,
  1937,
  1927,
  1927,
  1927,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1928,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1924,
  1924,
  1924,
  1924,
  1932,
  1932,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1800,
  1943,
  1943,
  1899,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1919,
  1953,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1914,
  1944,
  1944,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1921,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1920,
  1938,
  1938,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1913,
  1900,
  1900,
  1900,
  1900,
  1900,
  1900,
  1900,
  1900,
  1905,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1916,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1935,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1910,
  1963,
  1867,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1908,
  1912,
  1912,
  1912,
  1912,
  1912,
  1912,
  1912,
  1912,
  1912,
  1912,
  1912,
  1912,
  1912,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1892,
  1892,
  1892,
  1892,
  1892,
  1901,
  1890,
  1876,
  1876,
  1876,
  1876,
  1876,
  1876,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922],
 'The Book of Mormon': [1844,
  1844,
  1842,
  1903,
  1861,
  1861,
  1861,
  1861,
  1861,
  1889,
  1882,
  1882,
  1882,
  1848,
  1848,
  1843,
  1843,
  1843,
  1887,
  1909,
  1909,
  1909,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1880,
  1800,
  1800,
  1800,
  1888,
  1888,
  1899,
  1899,
  1899,
  1899,
  1899,
  1899,
  1899,
  1899,
  1899,
  1899,
  1899,
  1899,
  1899,
  1962,
  1879,
  1879,
  1914,
  1914,
  1918,
  1918,
  1918,
  1918,
  1913,
  1915,
  1893,
  1893,
  1910,
  1910,
  1908,
  1912,
  1912,
  1912,
  1912,
  1912,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1892,
  1901,
  1901,
  1901,
  1890,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1917,
  1922,
  1922,
  1922,
  1922,
  1866,
  1866,
  1850],
 'The Federalist Papers': [1787],
 'The Song of Hiawatha': [1903,
  1889,
  1882,
  1863,
  1902,
  1902,
  1906,
  1911,
  1855,
  1855,
  1855,
  1855,
  1855,
  1855,
  1880,
  1872,
  1919,
  1914,
  1913,
  1869,
  1916,
  1915,
  1904,
  1901,
  1883,
  1922],
 'Paradise Lost': [1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1753,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1789,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1779,
  1844,
  1809,
  1809,
  1809,
  1809,
  1809,
  1842,
  1842,
  1842,
  1842,
  1926,
  1926,
  1926,
  1783,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1765,
  1765,
  1765,
  1937,
  1851,
  1851,
  1851,
  1851,
  1851,
  1851,
  1851,
  1851,
  1851,
  1851,
  1851,
  1851,
  1851,
  1816,
  1816,
  1939,
  1813,
  1793,
  1861,
  1861,
  1861,
  1861,
  1861,
  1861,
  1861,
  1861,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1889,
  1882,
  1882,
  1882,
  1882,
  1882,
  1882,
  1882,
  1882,
  1882,
  1825,
  1835,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1896,
  1828,
  1828,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1863,
  1885,
  1885,
  1885,
  1885,
  1885,
  1885,
  1885,
  1885,
  1885,
  1885,
  1885,
  1885,
  1852,
  1852,
  1852,
  1852,
  1852,
  1852,
  1852,
  1852,
  1791,
  1791,
  1791,
  1848,
  1848,
  1848,
  1848,
  1848,
  1843,
  1843,
  1843,
  1843,
  1843,
  1843,
  1843,
  1843,
  1843,
  1843,
  1843,
  1843,
  1843,
  1843,
  1772,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1775,
  1775,
  1834,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1776,
  1877,
  1877,
  1877,
  1877,
  1877,
  1877,
  1877,
  1877,
  1877,
  1877,
  1877,
  1877,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1894,
  1930,
  1930,
  1930,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1887,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1855,
  1855,
  1855,
  1855,
  1855,
  1855,
  1855,
  1855,
  1855,
  1760,
  1928,
  1928,
  1928,
  1928,
  1799,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1838,
  1838,
  1838,
  1841,
  1841,
  1841,
  1810,
  1810,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1884,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1827,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1907,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1880,
  1833,
  1833,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  1800,
  ...],
 "Aesop's Fables\r\nTranslated by George Fyler Townsend": [],
 "Roget's Thesaurus": [1889,
  1889,
  1882,
  1907,
  1871,
  1805,
  1858,
  1873,
  1908,
  1912,
  1856],
 'Narrative of the Life of Frederick Douglass, an American Slave': [],
 'O Pioneers!': [1903,
  1903,
  1903,
  1855,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1924,
  1919,
  1919,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1918,
  1913,
  1900,
  1900,
  1900,
  1900,
  1900,
  1905,
  1910,
  1908,
  1922],
 'The 1991 CIA World Factbook': [],
 'Far from the Madding Crowd': [1923,
  1903,
  1885,
  1906,
  1887,
  1855,
  1855,
  1838,
  1907,
  1907,
  1897,
  1897,
  1897,
  1897,
  1888,
  1899,
  1899,
  1899,
  1854,
  1919,
  1919,
  1919,
  1868,
  1874,
  1874,
  1874,
  1914,
  1921,
  1918,
  1920,
  1913,
  1913,
  1913,
  1900,
  1900,
  1900,
  1916,
  1916,
  1916,
  1916,
  1916,
  1915,
  1893,
  1910,
  1910,
  1867,
  1912,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1904,
  1886,
  1886,
  1901,
  1876,
  1883,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922,
  1922],
 'The Fables of Aesop\r\nSelected, Told Anew, and Their History Traced': [],
 'The 1990 United States Census': [],
 'The Bible, King James Version, Complete': [],
 'Plays of Sophocles: Oedipus the King; Oedipus at Colonus; Antigone': [],
 'Herland': [1906,
  1865,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1915,
  1878,
  1824,
  1824,
  1824,
  1824,
  1824,
  1904,
  1968,
  1864],
 'The Scarlet Letter': [1926,
  1926,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1923,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1903,
  1851,
  1889,
  1889,
  1882,
  1896,
  1896,
  1863,
  1863,
  1863,
  1863,
  1885,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1925,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1902,
  1877,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1906,
  1894,
  1894,
  1894,
  1887,
  1887,
  1887,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1911,
  1928,
  1909,
  1909,
  1909,
  1909,
  1909,
  1909,
  1884,
  1884,
  1884,
  1884,
  1924,
  1924,
  1932,
  1932,
  1932,
  1932,
  1932,
  1932,
  1932,
  1932,
  1932,
  1932,
  1932,
  1932,
  1932,
  1932,
  1907,
  1907,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1897,
  1880,
  1880,
  1880,
  1888,
  1872,
  1872,

In [ ]:
extract_books_streaming(df, )

In [24]:
import pickle

# Remove empty entries and keep only the earliest year
published_year = {
    title: min(years)
    for title, years in published_year.items()
    if years
}

# Save to disk
with open("published_year.pkl", "wb") as f:
    pickle.dump(published_year, f)

In [18]:
import pickle
with open("../data/published_year.pkl", "rb") as f:
    published_year = pickle.load(f)

In [19]:
published_year

{'The United States Constitution': 1889,
 'Give Me Liberty or Give Me Death': 1901,
 'The Mayflower Compact': 1889,
 "Alice's Adventures in Wonderland": 1865,
 'Through the Looking-Glass': 1864,
 'The Hunting of the Snark: An Agony in Eight Fits': 1895,
 'Peter Pan': 1800,
 'The Book of Mormon': 1800,
 'The Federalist Papers': 1787,
 'The Song of Hiawatha': 1855,
 'Paradise Lost': 1753,
 "Roget's Thesaurus": 1805,
 'O Pioneers!': 1855,
 'Far from the Madding Crowd': 1838,
 'Herland': 1824,
 'The Scarlet Letter': 1822,
 'The Time Machine': 1895,
 'The War of the Worlds': 1892,
 'The Legend of Sleepy Hollow': 1800,
 'The Strange Case of Dr. Jekyll and Mr. Hyde': 1851,
 'The Song of the Lark': 1900,
 'Anne of Green Gables': 1908,
 'Anne of Avonlea': 1911,
 'Pi': 1750,
 'Anne of the Island': 1914,
 'The Marvelous Land of Oz': 1900,
 'The Wonderful Wizard of Oz': 1900,
 'Paradise Regained': 1753,
 'The Scarlet Pimpernel': 1875,
 'The Communist Manifesto': 1848,
 'A Princess of Mars': 1912,
 'The Gods of Mars': 1913,
 'On the Duty of Civil Disobedience': 1849,
 'Thuvia, Maid of Mars': 1916,
 'Adventures of Huckleberry Finn': 1853,
 'The House of the Seven Gables': 1850,
 'Tarzan of the Apes': 1890,
 'The Return of Tarzan': 1911,
 'Ivanhoe: A Romance': 1876,
 'The Beasts of Tarzan': 1914,
 "A Connecticut Yankee in King Arthur's Court": 1853,
 'The Son of Tarzan': 1916,
 'Tom Sawyer Abroad': 1853,
 'Tarzan and the Jewels of Opar': 1914,
 'Tom Sawyer, Detective': 1853,
 "Alexander's Bridge": 1861,
 'The Monster Men': 1913,
 'A Tale of Two Cities': 1815,
 'Collected Articles of Frederick Douglass': 1845,
 "The Tragedy of Pudd'nhead Wilson": 1882,
 'Around the World in Eighty Days': 1870,
 'Persuasion': 1759,
 'Jungle Tales of Tarzan': 1916,
 'The Return of Sherlock Holmes': 1894,
 'Freckles': 1773,
 'Violists': 1836,
 'The Secret Garden': 1898,
 'A Tramp Abroad': 1853,
 'Treasure Island': 1836,
 'Northanger Abbey': 1800,
 'The Return of the Native': 1859,
 "At the Earth's Core": 1914,
 'A Girl of the Limberlost': 1907,
 'The Arabian Nights Entertainments': 1880,
 'Orthodoxy': 1776,
 'The Art of War': 1753,
 'The Damnation of Theron Ware': 1870,
 'Les Misérables': 1822,
 "A Child's Garden of Verses": 1877,
 'The Lost World': 1894,
 'The Jungle': 1857,
 'Mansfield Park': 1800,
 'The Mayor of Casterbridge': 1863,
 'The Voyage Out': 1915,
 'Middlemarch': 1815,
 'Common Sense': 1750,
 'The Autobiography of Benjamin Franklin': 1848,
 'The Lost Continent': 1910,
 'The Republic': 1753,
 'The Rime of the Ancient Mariner': 1817,
 'Wild Justice': 1845,
 'Jude the Obscure': 1863,
 'The Rise of Silas Lapham': 1844,
 'The Moonstone': 1863,
 'Daddy-Long-Legs': 1845,
 'Emma': 1750,
 'Sense and Sensibility': 1811,
 'Flower Fables': 1848,
 'Twenty Thousand Leagues under the Sea': 1870,
 'Summer': 1753,
 'Charlotte Temple': 1775,
 'The Haunted Bookshop': 1919,
 'The Picture of Dorian Gray': 1890,
 'The Phantom of the Opera': 1911,
 'Roderick Hudson': 1844,
 'The American': 1753,
 'Confidence': 1753,
 'The Europeans': 1759,
 'My Bondage and My Freedom': 1855,
 "Uncle Tom's Cabin": 1815,
 'Daisy Miller: A Study': 1911,
 'The Turn of the Screw': 1850,
 'An International Episode': 1847,
 'The Aspern Papers': 1836,
 'The Man from Snowy River': 1896,
 'The call of the wild': 1875,
 'Sons and Lovers': 1863,
 'Heart of Darkness': 1863,
 'The Secret Sharer': 1887,
 'The Moon and Sixpence': 1863,
 'A pair of blue eyes': 1888,
 'At the Back of the North Wind': 1854,
 "Cicero's Orations": 1773,
 'Aeneidos': 1877,
 'The Aeneid': 1753,
 'Georgicon': 1906,
 'The Georgics': 1818,
 'Child Christopher and Goldilind the Fair': 1902,
 'The Jungle Book': 1880,
 'Dear Enemy': 1881,
 'My Ántonia': 1900,
 'A Study in Scarlet': 1890,
 'Life on the Mississippi': 1853,
 'The Rubaiyat of Omar Khayyam': 1900,
 'Troilus and Criseyde': 1800,
 'Ballads of a Cheechako': 1910,
 "An Introduction to the Study of Robert Browning's Poetry": 1859,
 'A Dome of Many-Coloured Glass': 1912,
 'The Collected Poems of Rupert Brooke': 1915,
 'Trees, and Other Poems': 1914,
 'The Touchstone': 1861,
 'Dream Days': 1895,
 'Black Beauty': 1850,
 'Records of a Family of Engineers': 1904,
 'The Reef': 1800,
 'The House of Mirth': 1891,
 'Remember the Alamo': 1879,
 'The Wind in the Willows': 1895,
 'The Golden Age': 1753,
 "Paul Prescott's Charge": 1867,
 'The Cash Boy': 1871,
 'The Flirt': 1859,
 'The Market-Place': 1845,
 'Tales from Two Hemispheres': 1870,
 'United States Declaration of Independence': 1776,
 'The Ballad of Reading Gaol': 1881,
 'Rhymes of a Rolling Stone': 1912,
 'Before Adam': 1841,
 'Bunner Sisters': 1900,
 'Children of the Night': 1897,
 'Rhymes of a Red Cross Man': 1912,
 'The Golden Road': 1908,
 'John Barleycorn': 1786,
 'The Ways of Men': 1904,
 'Moran of the Lady Letty': 1904,
 'A Knight of the Cumberland': 1907,
 'Steep Trails': 1919,
 'The Princess Aline': 1895,
 "A Heap o' Livin'": 1916,
 "Island Nights' Entertainments": 1893,
 "Where There's a Will": 1908,
 'The Mucker': 1857,
 'The Burial of the Guns': 1870,
 'Robert Louis Stevenson': 1753,
 'Indian Boyhood': 1904,
 'Old Indian Legends': 1915,
 'Old Indian Days': 1913,
 'Margaret Ogilvy': 1896,
 'Fables': 1753,
 'Dracula': 1815,
 'The Harvester': 1867,
 'Fanny Herself': 1918,
 'Of Human Bondage': 1863,
 'The Story of a Pioneer': 1929,
 'Beyond the City': 1850,
 'The Scarlet Car': 1870,
 "Miss Billy's Decision": 1913,
 'The Mad King': 1914,
 'The Land of Little Rain': 1903,
 'The Country of the Pointed Firs': 1896,
 'Fantastic Fables': 1870,
 'An Occurrence at Owl Creek Bridge': 1890,
 'Memories and Portraits': 1850,
 'The Lost Prince': 1882,
 'Virginibus Puerisque, and Other Papers': 1885,
 'The Crossing': 1766,
 'The Great God Pan': 1872,
 'The Song of Roland': 1856,
 'Jerusalem Delivered': 1789,
 'Cranford': 1766,
 'The Lady, or the Tiger?': 1870,
 "L'Allegro, Il Penseroso, Comus, and Lycidas": 1880,
 'The First Book of Adam and Eve': 1927,
 'Helen of Troy, and Other Poems': 1918,
 'Blix': 1830,
 'Penrod': 1861,
 'Soldiers of Fortune': 1753,
 'The Reporter Who Made Himself King': 1898,
 'The Souls of Black Folk': 1844,
 "The King's Jackal": 1870,
 'John Jacob Astor': 1791,
 'Ballads': 1753,
 'The Pageant of Summer': 1844,
 'The Magic of Oz': 1900,
 'Dorothy and the Wizard in Oz': 1900,
 'Kidnapped': 1800,
 'The Romany Rye': 1822,
 'General William Booth Enters into Heaven, and Other Poems': 1922,
 'Familiar Studies of Men and Books': 1800,
 'Tales and Fantasies': 1890,
 'The Great War Syndicate': 1870,
 'The Fortune Hunter': 1868,
 'The Ambassadors': 1794,
 'The Conflict': 1800,
 'The Circular Staircase': 1890,
 'Underwoods': 1817,
 'The Vital Message': 1900,
 'Just David': 1908,
 'Love Songs': 1865,
 'The Love Affairs of a Bibliomaniac': 1892,
 'The crowd': 1750,
 'A Book of Remarkable Criminals': 1928,
 'Maggie: A Girl of the Streets': 1897,
 'The Psychology of Revolution': 1908,
 'Susan Lenox: Her Fall and Rise': 1923,
 'The Shadow Line: A Confession': 1923,
 'The Breitmann Ballads': 1872,
 'The University of Hard Knocks': 1918,
 'The Price She Paid': 1904,
 'Dreams and Dust': 1918,
 'The White People': 1808,
 'The Dawn of a To-morrow': 1921,
 'The Quest of the Golden Girl: A Romance': 1915,
 'The Mountains': 1768,
 'The Princess of Cleves': 1789,
 'Manon Lescaut': 1791,
 'Heretics': 1753,
 'The Bride of Lammermoor': 1800,
 'The House Behind the Cedars': 1899,
 'Stories to Tell to Children': 1905,
 'In Darkest England, and the Way Out': 1889,
 'Criminal Sociology': 1890,
 'The Cost': 1797,
 'Little Lord Fauntleroy': 1800,
 "In the Bishop's Carriage": 1906,
 'The Woodlanders': 1887,
 'The Conquest of Canaan': 1890,
 'The Road to Oz': 1900,
 'Rezanov': 1906,
 'Essays in the Art of Writing': 1894,
 'To-morrow': 1750,
 'Amy Foster': 1887,
 'The Little Lame Prince': 1867,
 'Tracks of a Rolling Stone': 1905,
 'Rebecca of Sunnybrook Farm': 1894,
 'The Adventures of Pinocchio': 1937,
 'Desert Gold': 1913,
 'The Blue Fairy Book': 1857,
 'The Fifth String': 1901,
 'History of the Warfare of Science with Theology in Christendom': 1873,
 'The Shuttle': 1827,
 'Adam Bede': 1816,
 'Twice-Told Tales': 1826,
 'Mosses from an old manse': 1899,
 'Little Women': 1800,
 'The Silverado Squatters': 1885,
 'The Emerald City of Oz': 1900,
 'A Kidnapped Santa Claus': 1904,
 'The Life and Adventures of Santa Claus': 1902,
 'The Life and Adventures of Robinson Crusoe': 1876,
 'The Chinese Boy and Girl': 1902,
 'The End of the Tether': 1887,
 'At the Foot of the Rainbow': 1900,
 'The Song of the Cardinal': 1903,
 'An Inland Voyage': 1879,
 'A Footnote to History: Eight Years of Trouble in Samoa': 1890,
 'Tales of Terror and Mystery': 1919,
 'Jean of the Lazy A': 1908,
 'The Red Fairy Book': 1857,
 'The Age of Innocence': 1863,
 'Main Street': 1835,
 "Anne's House of Dreams": 1910,
 'Silas Marner': 1822,
 'The People That Time Forgot': 1950,
 "Out of Time's Abyss": 1914,
 'The Contrast': 1777,
 'The Unbearable Bassington': 1922,
 'Rewards and Fairies': 1892,
 "Puck of Pook's Hill": 1901,
 'The Thirty-Nine Steps': 1915,
 'Greenmantle': 1900,
 'Mr. Standfast': 1888,
 'The Further Adventures of Robinson Crusoe': 1925,
 'The Mystery of Edwin Drood': 1867,
 'The Zincali: An Account of the Gypsies of Spain': 1903,
 'Tales from Shakespeare': 1822,
 'Poems of William Blake': 1783,
 'The Poems of Sidney Lanier': 1918,
 'The Pickwick Papers': 1814,
 'The Woman in White': 1815,
 'Religio Medici, Hydriotaphia, and the Letter to a Friend': 1868,
 "Danny's Own Story": 1922,
 "Master Humphrey's Clock": 1789,
 'Catriona': 1823,
 'Flame and Shadow': 1911,
 'Twilight Stories': 1857,
 'Rivers to the Sea': 1885,
 'Vanity Fair': 1754,
 'Notes from the Underground': 1864,
 'Gulliver of Mars': 1905,
 'Pellucidar': 1914,
 'Idylls of the King': 1796,
 'Prester John': 1775,
 'Orlando Furioso': 1753,
 'Poems': 1753,
 'The Warden': 1753,
 'Sylvie and Bruno': 1889,
 'Ponkapog Papers': 1903,
 'Essays of Travel': 1894,
 'An Outcast of the Islands': 1887,
 'The Yellow Fairy Book': 1857,
 'The Violet Fairy Book': 1903,
 'The Altar of the Dead': 1916,
 'The Death of the Lion': 1900,
 "The Haunted Man and the Ghost's Bargain": 1882,
 'The Figure in the Carpet': 1896,
 'The Dynamiter': 1885,
 'Wild Wales: Its People, Language and Scenery': 1914,
 'Ancient Poems, Ballads, and Songs of the Peasantry of England': 1890,
 'Pictures from Italy': 1836,
 'Phantasmagoria and Other Poems': 1893,
 'Rasselas, Prince of Abyssinia': 1776,
 'Grace Abounding to the Chief of Sinners': 1858,
 'Life and Letters of Robert Browning': 1844,
 'Life of Robert Browning': 1859,
 'The Anglo-Saxon Chronicle': 1800,
 'The Fall of Troy': 1800,
 'Phil, the Fiddler': 1872,
 "The Gutenberg Webster's Unabridged Dictionary": 1999,
 'American Notes': 1814,
 'The Battle of Life': 1833,
 'The Golden Threshold': 1916,
 'Creatures That Once Were Men': 1912,
 'The Compleat Angler': 1789,
 'A Personal Record': 1880,
 'The Goodness of St. Rocque, and Other Stories': 1918,
 'Proposed Roads to Freedom': 1920,
 'Glaucus; Or, The Wonders of the Shore': 1863,
 'The Castle of Otranto': 1764,
 'The Light Princess': 1887,
 'Memoir of Fleeming Jenkin': 1885,
 "A Child's History of England": 1851,
 'The Old Curiosity Shop': 1822,
 'The King of the Golden River': 1840,
 'Lucasta': 1857,
 'The Mansion': 1782,
 'The Roadmender': 1887,
 'The Amateur Cracksman': 1901,
 'The Princess and the Goblin': 1872,
 'The Princess and Curdie': 1832,
 'Allan Quatermain': 1851,
 'The Cruise of the Jasper B.': 1918,
 'Chita: A Memory of Last Island': 1880,
 'Tono-Bungay': 1844,
 "Almayer's Folly: A Story of an Eastern River": 1924,
 "The Birds' Christmas Carol": 1886,
 'Henry James, Jr.': 1870,
 'Men of Invention and Industry': 1916,
 'The Star-Spangled Banner': 1843,
 'Emile Zola': 1844,
 'Oliver Twist': 1797,
 'Editorials from the Hearst Newspapers': 1921,
 'The Golden Mean': 1837,
 'Burning Daylight': 1902,
 'Anomalies and Curiosities of Medicine': 1904,
 'The Autocrat of the Breakfast-Table': 1823,
 "A Young Girl's Diary": 1922,
 'Arizona nights': 1908,
 'The Story of Mankind': 1921,
 "A Lady's Life in the Rocky Mountains": 1883,
 'Arizona Sketches': 1906,
 'James Pethel': 1880,
 'The Moon Pool': 1919,
 'David Copperfield': 1800,
 'Agnes Grey': 1823,
 'Wuthering Heights': 1815,
 'The Book of Tea': 1903,
 'Moral Emblems': 1839,
 'Essays and Lectures': 1872,
 'When the Sleeper Wakes': 1897,
 'Five Children and It': 1902,
 'The War in the Air': 1899,
 'The Travels of Sir John Mandeville': 1896,
 'The Lost City': 1881,
 'On the Nature of Things': 1818,
 'Hard Times': 1815,
 'The Red One': 1903,
 'The Gathering of Brother Hilarius': 1900,
 "Lady Windermere's Fan": 1896,
 'The Princess': 1750,
 'Les Cenci': 1909,
 'Vittoria Accoramboni': 1886,
 'This Side of Paradise': 1900,
 'Philoktetes': 1846,
 'Holiday Romance': 1851,
 "George Silverman's Explanation": 1851,
 'Hunting Sketches': 1879,
 'The History of the Telephone': 1911,
 'Dombey and Son': 1814,
 'Speeches: Literary and Social': 1887,
 "Gulliver's Travels into Several Remote Nations of the World": 1909,
 'The Argonautica': 1870,
 'Robin Hood': 1753,
 'The Theory of the Leisure Class': 1863,
 'The Memoirs of Sherlock Holmes': 1877,
 'The Phoenix and the Carpet': 1910,
 'The Story of the Amulet': 1906,
 'New Arabian Nights': 1861,
 'Men, Women and Ghosts': 1916,
 'The Life of General Francis Marion': 1818,
 'Lays of Ancient Rome': 1800,
 'Tom Grogan': 1815,
 'A Woman of No Importance': 1893,
 'Clocks': 1756,
 'Dreams': 1751,
 'Evergreens': 1800,
 'Stage-Land': 1894,
 'Polly of the Circus': 1901,
 'Baby Mine': 1883,
 'The Mysterious Affair at Styles': 1916,
 'Passing of the Third Floor Back': 1901,
 'Reprinted Pieces': 1840,
 'A House of Pomegranates': 1881,
 'The Duchess of Padua': 1883,
 'Little Britain': 1753,
 'Yankee Gypsies': 1882,
 'My Garden Acquaintance': 1848,
 'Our Mutual Friend': 1815,
 'An Ideal Husband': 1850,
 'Letters from the Cape': 1865,
 'Intentions': 1753,
 'The Lazy Tour of Two Idle Apprentices': 1815,
 'The Rose and the Ring': 1848,
 'The Lesson of the Master': 1850,
 'The Jew of Malta': 1850,
 'The White Company': 1877,
 "Her Father's Daughter": 1909,
 'Abraham Lincoln': 1830,
 'Treatise on Parents and Children': 1911,
 'White Fang': 1890,
 'Tales of the Fish Patrol': 1907,
 'A Hero of Our Time': 1906,
 'The Uncommercial Traveller': 1815,
 'Library Work with Children': 1917,
 'Sketches of Young Couples': 1887,
 'Sketches of Young Gentlemen': 1836,
 'De Profundis': 1784,
 'The Lamplighter': 1800,
 'The Bab Ballads': 1878,
 'The Fall of the House of Usher': 1839,
 'More Bab Ballads': 1898,
 'Songs of a Savoyard': 1883,
 'The Village Watch-Tower': 1904,
 'Good Indian': 1834,
 'Just Folks': 1911,
 'Misalliance': 1829,
 'The Voyage of the Beagle': 1870,
 'Dust': 1751,
 'Lady Susan': 1765,
 'The Patchwork Girl of Oz': 1900,
 'Tik-Tok of Oz': 1900,
 'The Scarecrow of Oz': 1900,
 'The Lost Princess of Oz': 1900,
 'Little Dorrit': 1815,
 'The Merry Adventures of Robin Hood': 1895,
 'The black tulip': 1848,
 'Maid Marian': 1800,
 'Nicholas Nickleby': 1814,
 'Martin Chuzzlewit': 1815,
 'The Tenant of Wildfell Hall': 1823,
 "The Devil's Dictionary": 1906,
 'The Secret Agent: A Simple Tale': 1924,
 'Tanglewood Tales': 1848,
 'Alice Adams': 1864,
 'Beowulf': 1800,
 'The Book of Nonsense': 1840,
 'Father Sergius': 1889,
 'Master and Man': 1753,
 'The Education of the Child': 1886,
 'Riders to the Sea': 1904,
 'Ballads of a Bohemian': 1912,
 'Don Quixote': 1753,
 'The First Men in the Moon': 1899,
 'The Lure of the Dim Trails': 1906,
 'On the Improvement of the Understanding': 1905,
 'The Soul of Man under Socialism': 1905,
 'The Water-Babies': 1858,
 'Poems by Currer, Ellis, and Acton Bell': 1887,
 'Sword Blades and Poppy Seed': 1912,
 'Walking': 1763,
 'Bleak House': 1805,
 'The Wrecker': 1850,
 'The Diary of a Nobody': 1910,
 'The Professor': 1753,
 'The Night-Born': 1903,
 'The Pupil': 1815,
 "Rose o' the River": 1886,
 'Joe Wilson and His Mates': 1900,
 'Style': 1751,
 'Missionary Travels and Researches in South Africa': 1858,
 "Shakespeare's Sonnets": 1774,
 'The Story of Evolution': 1913,
 "Extract from Captain Stormfield's Visit to Heaven": 1916,
 'Venus and Adonis': 1753,
 'God, the Invisible King': 1903,
 'The New Machiavelli': 1899,
 'The Dark Lady of the Sonnets': 1910,
 'Within the Tides: Tales': 1924,
 'A Collection of Ballads': 1855,
 'Martin Eden': 1908,
 'The Mirror of the Sea': 1887,
 'The World Set Free': 1886,
 'Grass of Parnassus': 1818,
 'The Cask of Amontillado': 1845,
 'The Masque of the Red Death': 1842,
 'The Raven': 1782,
 'William the Conqueror': 1753,
 'No title': 1787,
 'The Sea-Wolf': 1902,
 'The Strength of the Strong': 1903,
 'The Wallet of Kai Lung': 1900,
 'The Scouts of the Valley': 1908,
 'The Life and Opinions of Tristram Shandy, Gentleman': 1905,
 'Dead Souls': 1845,
 'Life of John Sterling': 1800,
 "A Horse's Tale": 1853,
 'Rolf in the Woods': 1913,
 'On Heroes, Hero-Worship, and the Heroic in History': 1881,
 'The Beast in the Jungle': 1916,
 'The Faith of Men': 1905,
 "Mrs. Warren's Profession": 1903,
 'The Riverman': 1880,
 'King Richard III': 1762,
 'The Comedy of Errors': 1753,
 'The Sonnets': 1800,
 'The Tragedy of Titus Andronicus': 1999,
 'The Taming of the Shrew': 1776,
 'The Two Gentlemen of Verona': 1753,
 "Love's Labour's Lost": 1776,
 'King John': 1753,
 'King Richard the Second': 1776,
 "A Midsummer Night's Dream": 1800,
 'The Merchant of Venice': 1753,
 'The Merry Wives of Windsor': 1753,
 'Second Part of King Henry IV': 1852,
 'Much Ado about Nothing': 1753,
 'As You Like It': 1771,
 'The Tragedy of Hamlet, Prince of Denmark': 1842,
 'Troilus and Cressida': 1753,
 "All's Well That Ends Well": 1800,
 'Measure for Measure': 1753,
 'The Tragedy of Macbeth': 1753,
 'The Tragedy of Coriolanus': 1884,
 'Cymbeline': 1753,
 "The Winter's Tale": 1753,
 'The Tempest': 1753,
 'King Henry the Eighth': 1775,
 "A Lover's Complaint": 1800,
 'The Research Magnificent': 1899,
 'Latter-Day Pamphlets': 1800,
 'Typhoon': 1800,
 'In the Cage': 1897,
 'The Journal of a Voyage to Lisbon': 1914,
 'The Nibelungenlied': 1882,
 'Babbitt': 1848,
 'Penrod and Sam': 1900,
 'Fire-Tongue': 1921,
 'The Game': 1751,
 'Jerry of the Islands': 1900,
 'Adventure': 1751,
 'The iron heel': 1866,
 'A Strange Disappearance': 1883,
 'The Pool in the Desert': 1903,
 'Agesilaus': 1753,
 'Anabasis': 1776,
 'The Apology': 1800,
 'The Economist': 1810,
 'Hellenica': 1800,
 'Hiero': 1753,
 'The Memorabilia': 1874,
 'The Symposium': 1800,
 'Dope': 1886,
 'The Return of Dr. Fu-Manchu': 1963,
 'The Count of Monte Cristo': 1840,
 'War of the Classes': 1902,
 'The Lair of the White Worm': 1911,
 'The Message': 1815,
 'The Jolly Corner': 1916,
 'The Coxon Fund': 1894,
 'The Adventures of Louis de Rougemont': 1908,
 'Glasses': 1753,
 'The Purse': 1850,
 'An Anthology of Australian Verse': 1911,
 'Gargantua and Pantagruel': 1760,
 'An Essay on the Trial By Jury': 1852,
 'Tales of Unrest': 1898,
 'Dolly Dialogues': 1894,
 'Cabin Fever': 1914,
 'The Colour of Life': 1896,
 'Nada the Lily': 1892,
 'South Sea Tales': 1903,
 'History of the Conquest of Peru': 1843,
 'A Selection from the Lyrical Poems of Robert Herrick': 1891,
 'The Man That Corrupted Hadleyburg': 1853,
 'The Street of Seven Stars': 1908,
 'The Elixir of Life': 1851,
 'The Adventures of Jimmie Dale': 1922,
 "Cobb's Anatomy": 1913,
 'Ursula': 1759,
 'Sidney Lanier': 1870,
 'Faraday as a Discoverer': 1845,
 'The Expression of the Emotions in Man and Animals': 1889,
 'Select Poems of Sidney Lanier': 1870,
 'Pierre Grassou': 1884,
 'On the Track': 1869,
 'The Prince': 1750,
 'Captain Fracasse': 1860,
 'Father Goriot': 1895,
 'The City of Dreadful Night': 1870,
 'Unconscious Comedians': 1904,
 'Night and Day': 1753,
 'Second April': 1922,
 'Anthem': 1751,
 'Cyrano de Bergerac': 1766,
 'The three musketeers': 1894,
 'Ten Years Later': 1840,
 'Twenty years after': 1800,
 'Betty Zane': 1903,
 'The Glimpses of the Moon': 1918,

In [26]:
df_filtered = df_raw[df_raw["Title"].isin(published_year.keys())]
df_filtered["published_year"] = df_filtered["Title"].map(published_year)

In [27]:
df_filtered

,Etext Number,Type,Issued,Title,Language,LoCC,Bookshelves,Authors,rights,Subjects,...,EPUB (older E-readers),"EPUB (no images, older E-readers)",Kindle,Kindle (E-readers incl. Send-to-Kindle),"Kindle (no images, older E-readers)",Plain Text UTF-8,Download HTML(zip),Resource Description Framework (RDF),Other Links,published_year
4,5,Text,1975-12-01,The United States Constitution,en,JK; KF,United States; Politics; American Revolutionar...,United States,Public domain in the USA.,JK ; United States. Constitution ; United Stat...,...,https://www.gutenberg.org/ebooks/5.epub.images,https://www.gutenberg.org/ebooks/5.epub.noimages,https://www.gutenberg.org/ebooks/5.kf8.images,https://www.gutenberg.org/ebooks/5.kindle.images,https://www.gutenberg.org/ebooks/5.kindle.noim...,https://www.gutenberg.org/ebooks/5.txt.utf-8,https://www.gutenberg.org/files/5/5-h.zip,https://www.gutenberg.org/ebooks/5.rdf,https://www.gutenberg.org/files/5/5.txt ; http...,1889
5,6,Text,1976-12-01,Give Me Liberty or Give Me Death,en,E201,American Revolutionary War; Browsing: History ...,"Henry, Patrick",Public domain in the USA.,E201 ; United States -- Politics and governmen...,...,https://www.gutenberg.org/ebooks/6.epub.images,https://www.gutenberg.org/ebooks/6.epub.noimages,https://www.gutenberg.org/ebooks/6.kf8.images,https://www.gutenberg.org/ebooks/6.kindle.images,https://www.gutenberg.org/ebooks/6.kindle.noim...,https://www.gutenberg.org/ebooks/6.txt.utf-8,https://www.gutenberg.org/cache/epub/6/pg6-h.zip,https://www.gutenberg.org/ebooks/6.rdf,https://www.gutenberg.org/files/6/6.zip ; http...,1901
6,7,Text,1977-12-01,The Mayflower Compact,en,F001,Browsing: History - American,NaN,Public domain in the USA.,Mayflower Compact (1620) ; Massachusetts -- Hi...,...,https://www.gutenberg.org/ebooks/7.epub.images,https://www.gutenberg.org/ebooks/7.epub.noimages,https://www.gutenberg.org/ebooks/7.kf8.images,https://www.gutenberg.org/ebooks/7.kindle.images,https://www.gutenberg.org/ebooks/7.kindle.noim...,https://www.gutenberg.org/ebooks/7.txt.utf-8,https://www.gutenberg.org/cache/epub/7/pg7-h.zip,https://www.gutenberg.org/ebooks/7.rdf,https://www.gutenberg.org/files/7/7-0.txt ; ht...,1889
10,11,Text,2008-06-27,Alice's Adventures in Wonderland,en,PR; PZ,Children's Literature; Browsing: Children & Yo...,"Carroll, Lewis",Public domain in the USA.,Imaginary places -- Juvenile fiction ; Childre...,...,https://www.gutenberg.org/ebooks/11.epub.images,https://www.gutenberg.org/ebooks/11.epub.noimages,https://www.gutenberg.org/ebooks/11.kf8.images,https://www.gutenberg.org/ebooks/11.kindle.images,https://www.gutenberg.org/ebooks/11.kindle.noi...,https://www.gutenberg.org/ebooks/11.txt.utf-8,https://www.gutenberg.org/cache/epub/11/pg11-h...,https://www.gutenberg.org/ebooks/11.rdf,https://www.gutenberg.org/files/11/11-h/11-h.h...,1865
11,12,Text,2008-06-25,Through the Looking-Glass,en,PR; PZ,Children's Literature; Best Books Ever Listing...,"Carroll, Lewis",Public domain in the USA.,Imaginary places -- Juvenile fiction ; Childre...,...,https://www.gutenberg.org/ebooks/12.epub.images,https://www.gutenberg.org/ebooks/12.epub.noimages,https://www.gutenberg.org/ebooks/12.kf8.images,https://www.gutenberg.org/ebooks/12.kindle.images,https://www.gutenberg.org/ebooks/12.kindle.noi...,https://www.gutenberg.org/ebooks/12.txt.utf-8,https://www.gutenberg.org/cache/epub/12/pg12-h...,https://www.gutenberg.org/ebooks/12.rdf,https://www.gutenberg.org/files/12/12-h/12-h.h...,1864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75370,75546,Text,2025-03-06,The real Mackay,en,PR,NaN,"Mackenzie, Donald A. (Donald Alexander)",Public domain in the USA.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.gutenberg.org/files/75546/75546-0....,1922
75371,75547,Text,2025-03-07,Beauvallet,en,NaN,NaN,"Heyer, Georgette",Public domain in the USA.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.gutenberg.org/files/75547/75547-h/...,1885
75375,75551,Text,2025-03-07,Reminiscences of the South Seas,en,NaN,NaN,"La Farge, John",Public domain in the USA.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.gutenberg.org/files/75551/75551-h/...,1921
75376,75552,Text,2025-03-08,Wild oats,en,NaN,NaN,"Oppenheim, James",Public domain in the USA.,Physicians -- Fiction ; PS ; United States -- ...,...,https://www.gutenberg.org/ebooks/75552.epub.im...,https://www.gutenberg.org/ebooks/75552.epub.no...,https://www.gutenberg.org/ebooks/75552.kf8.images,https://www.gutenberg.org/ebooks/75552.kindle....,NaN,https://www.gutenberg.org/ebooks/75552.txt.utf-8,https://www.gutenberg.org/cache/epub/75552/pg7...,https://www.gutenberg.org/ebooks/75552.rdf,https://www.gutenberg.org/files/75552/75552-h/...,1818
75388,75564,Text,2025-03-08,The puzzle of life,en,NaN,NaN,"Nicols, Arthur",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925

In [28]:
df_filtered.to_csv("GP_1750_2000.csv", index=False)

In [29]:
opium_filenames = []
missing_files = []

for fn in tqdm(df_filtered["Etext Number"]):
    full_path = os.path.join(path + "books", str(fn))
    try:
        with open(full_path) as f:
            if 'opium' in f.read():
                opium_filenames.append(fn)
    except FileNotFoundError:
        missing_files.append(fn)

print(f"Found {len(opium_filenames)} opium files, {len(missing_files)} missing files")

  0%|          | 0/16958 [00:00<?, ?it/s]

Found 1533 opium files, 8 missing files

In [30]:
poppy_filenames = []
missing_files = []

for fn in tqdm(df_filtered["Etext Number"]):
    full_path = os.path.join(path + "books", str(fn))
    try:
        with open(full_path) as f:
            if 'poppy' in f.read() or "poppies" in f.read():
                poppy_filenames.append(fn)
    except FileNotFoundError:
        missing_files.append(fn)

print(f"Found {len(poppy_filenames)} poopy files, {len(missing_files)} missing files")

  0%|          | 0/16958 [00:00<?, ?it/s]

Found 1136 poopy files, 8 missing files

In [31]:
anodyne_filenames = []
missing_files = []

for fn in tqdm(df_filtered["Etext Number"]):
    full_path = os.path.join(path + "books", str(fn))
    try:
        with open(full_path) as f:
            if 'anodyne' in f.read():
                anodyne_filenames.append(fn)
    except FileNotFoundError:
        missing_files.append(fn)

print(f"Found {len(anodyne_filenames)} anodyne files, {len(missing_files)} missing files")

  0%|          | 0/16958 [00:00<?, ?it/s]

Found 432 anodyne files, 8 missing files

In [32]:
opium_derivative_filenames = []
missing_files = []

derivative_names = ["laudanum", "morphine", "codein", "heroin"]

for fn in tqdm(df_filtered["Etext Number"]):
    full_path = os.path.join(path + "books", str(fn))
    try:
        with open(full_path) as f:
            for word in derivative_names:
                if word in f.read():
                    opium_derivative_filenames.append(fn)
    except FileNotFoundError:
        missing_files.append(fn)

print(f"Found {len(opium_derivative_filenames)} files with opium derivative mentions, {len(missing_files)} missing files")

  0%|          | 0/16958 [00:00<?, ?it/s]

Found 368 files with opium derivative mentions, 8 missing files

In [33]:
print(f"There are {len(opium_filenames)} files that mention opium.")
print(f"There are {len(poppy_filenames)} files that mention poppy.")
print(f"There are {len(anodyne_filenames)} files that mention anodyne.")
print(f"There are {len(set(opium_filenames) & set(poppy_filenames))} files that mention opium and poppy.")
print(f"There are {len(set(opium_filenames) & set(anodyne_filenames))} files that mention opium and anodyne.")
print(f"There are {len(set(poppy_filenames) & set(anodyne_filenames))} files that mention poppy and anodyne.")
print(f"There are {len(set(opium_filenames) & set(poppy_filenames) & set(anodyne_filenames))} files that mention the 3 terms.")

print(f"\nIn total, we have {len(set(opium_filenames) | set(poppy_filenames) | set(anodyne_filenames))} books that mention some type of opium.")

There are 1533 files that mention opium.
There are 1136 files that mention poppy.
There are 432 files that mention anodyne.
There are 241 files that mention opium and poppy.
There are 114 files that mention opium and anodyne.
There are 76 files that mention poppy and anodyne.
There are 32 files that mention the 3 terms.

In total, we have 2702 books that mention some type of opium.

In [34]:
all_mentions = set(opium_filenames) | set(poppy_filenames) | set(anodyne_filenames)
opium_df = df_filtered[df_filtered["Etext Number"].isin(all_mentions)]

In [35]:
opium_df.Language.value_counts()

Language
en         2614
fr           67
fi            8
nl            6
la            3
en; kha       1
de            1
es            1
en; es        1
Name: count, dtype: int64

In [36]:
opium_df.Authors.value_counts()

Authors
Balzac, Honoré de                                                27
Doyle, Arthur Conan                                              21
Kipling, Rudyard                                                 19
Dickens, Charles                                                 16
MacDonald, George                                                16
                                                                 ..
Stuart, Henry Longan                                              1
Fowler, H. W. (Henry Watson) ; Fowler, F. G. (Francis George)     1
Herter, Albert ; Metchnikoff, Élie                                1
Nathan, George Jean ; Mencken, H. L. (Henry Louis)                1
La Farge, John                                                    1
Name: count, Length: 1590, dtype: int64

In [37]:
opium_df.Bookshelves.value_counts()

Bookshelves
Browsing: Culture/Civilization/Society; Browsing: Literature; Browsing: Fiction         354
Browsing: Literature; Browsing: Fiction                                                 270
Browsing: Literature; Browsing: Poetry                                                   97
Browsing: Crime/Mystery; Browsing: Literature; Browsing: Fiction                         68
Browsing: Biographies; Browsing: Literature                                              45
                                                                                       ...
Browsing: Philosophy & Ethics; Browsing: Research Methods/Statistics/Information Sys      1
Browsing: Culture/Civilization/Society; Browsing: History - Ancient                       1
Browsing: History - Warfare                                                               1
Browsing: Sociology                                                                       1
Browsing: Art & Photography; Browsing: History - General                                  1
Name: count, Length: 771, dtype: int64

In [38]:
opium_df.Title.value_counts()

Title
Poems                              14
The Iliad                           4
The Secret Garden                   3
The Picture of Dorian Gray          3
The Land of Little Rain             3
                                   ..
The nature of man                   1
Pistols for two                     1
From the four winds                 1
The real Mackay                     1
Reminiscences of the South Seas     1
Name: count, Length: 2610, dtype: int64

In [40]:
opium_df.value_counts()

Etext Number  Type  Issued      Title                       Language  LoCC  Bookshelves                                                                                                                                                      Authors                                 rights                     Subjects                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Read online (web)                                   EPUB3 (E-readers incl. Send-to-Kindle)               EPUB (older E-readers)                              EPUB (no images, older E-readers)                     Kindle                                             Kindle (E-readers incl. Send-to-Kindle)               Kindle (no images, older E-readers)                     Plain Text UTF-8                                  Download HTML(zip)                                        Resource Description Framework (RDF)        Other Links                                                                                                                                                                                                                                                                  published_year
22            Text  1991-12-01  Roget's Thesaurus           en        PE    Reference; Browsing: Encyclopedias/Dictionaries/Reference; Browsing: Language & Communication; Browsing: Literature                                              Roget, Peter Mark                       Public domain in the USA.  English language -- Synonyms and antonyms ; PE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         https://www.gutenberg.org/ebooks/22.html.images     https://www.gutenberg.org/ebooks/22.epub3.images     https://www.gutenberg.org/ebooks/22.epub.images     https://www.gutenberg.org/ebooks/22.epub.noimages     https://www.gutenberg.org/ebooks/22.kf8.images     https://www.gutenberg.org/ebooks/22.kindle.images     https://www.gutenberg.org/ebooks/22.kindle.noimages     https://www.gutenberg.org/ebooks/22.txt.utf-8     https://www.gutenberg.org/files/22/22-h.zip               https://www.gutenberg.org/ebooks/22.rdf     https://www.gutenberg.org/cache/epub/22/pg22.cover.small.jpg ; https://www.gutenberg.org/files/22/22-0.txt ; https://www.gutenberg.org/files/22/22-h/22-h.htm ; https://www.gutenberg.org/cache/epub/22/pg22.cover.medium.jpg ; https://www.gutenberg.org/files/22/22-0.zip  1805              1
24            Text  2008-06-27  O Pioneers!                 en        PS    Browsing: Culture/Civilization/Society; Browsing: History - American; Browsing: Literature; Browsing: Fiction                                                    Cather, Willa                           Public domain in the USA.  Swedish Americans -- Fiction ; Frontier and pioneer life -- Nebraska -- Fiction ; Women immigrants -- Fiction ; Nebraska -- Fiction ; Women farmers -- Fiction ; Farm life -- Fiction ; PS ; Historical fiction ; Siblings -- Fiction ; Women pioneers -- Fiction ; Domestic fiction                                                                                                                                                                                                                                                                                                                                   https://www.gutenberg.org/ebooks/24.html.images     https://www.gutenberg.org/ebooks/24.epub3.images     https://www.gutenberg.org/ebooks/24.epub.images     https://www.gutenberg.org/ebooks/24.epub.noimages     https://www.gutenberg.org/ebooks/24.kf8.images     https://www.gutenberg.org/ebooks/24.kindle.images     https://www.gutenberg.org/ebooks/24.kindle.noimages     https://www.gutenberg.org/ebooks/24.txt.utf-8     https://www.gutenberg.org/files/24/24-h.zip               https://www.gutenberg.org/ebooks/24.rdf     https://www.gutenberg.org/files/24/24-0.zip ; https://www.gutenberg.org/files/24/24-h/24-h.htm ; https://www.gutenberg.org/cache/epub/24/pg24.cover.small.jpg ; https://www.gutenberg.org/files/24/24-0.txt ; https://www.gutenberg.org/cache/epub/24/pg24.cover.medium.jpg  1855              1
44            Text  2008-06-27  The Song of the Lark        en        PS    Opera; Browsing: Culture/Civilization/Society; Browsing: Literature; Browsing: Fiction                                                                           Cather, Willa                           Public domain in the USA.  Opera -- Fiction ; Chicago (Ill.) -- Fiction ; Colorado -- Fiction ; Swedish Americans -- Fiction ; Young women -- Fiction ; Women singers -- Fiction ; PS ; Bildungsromans ; Children of clergy -- Fiction ; Musical fiction                                                                                                                                                                                                                                                                                                                                                                                          https://www.gutenberg.org/ebooks/44.html.images     https://www.gutenberg.org/ebooks/44.epub3.images     https://www.gutenberg.org/ebooks/44.epub.images     https://www.gutenberg.org/ebooks/44.epub.noimages     https://www.gutenberg.org/ebooks/44.kf8.images     https://www.gutenberg.org/ebooks/44.kindle.images     https://www.gutenberg.org/ebooks/44.kindle.noimages     https://www.gutenberg.org/ebooks/44.txt.utf-8     https://www.gutenberg.org/files/44/44-h.zip               https://www.gutenberg.org/ebooks/44.rdf     https://www.gutenberg.org/cache/epub/44/pg44.cover.medium.jpg ; https://www.gutenberg.org/files/44/44-0.txt ; https://www.gutenberg.org/files/44/44-0.zip ; https://www.gutenberg.org/cache/epub/44/pg44.cover.small.jpg ; https://www.gutenberg.org/files/44/44-h/44-h.htm  1900              1
45            Text  2008-06-27  Anne of Green Gables        en        PZ    Canada; Children's Literature; Browsing: Children & Young Adult Reading; Browsing: Culture/Civilization/Society; Browsing: History - General; Browsing: Fiction  Montgomery, L. M. (Lucy Maud)           Public domain in the USA.  Canada -- History -- 1867-1914 -- Fiction ; Country life -- Prince Edward Island -- Fiction ; Girls -- Fiction ; Prince Edward Island -- History -- 20th century -- Fiction ; PZ ; Orphans -- Fiction ; Islands -- Fiction ; Shirley, Anne (Fictitious character) -- Fiction ; Bildungsromans ; Friendship -- Fiction                                                                                                                                                                                                                                                                                                  https://www.gutenberg.org/ebooks/45.html.images     https://www.gutenberg.org/ebooks/45.epub3.images     https://www.gutenberg.org/ebooks/45.epub.images     https://www.gutenberg.org/ebooks/45.epub.noimages     https://www.gutenberg.org/ebooks/45.kf8.images     https://www.gutenberg.org/ebooks/45.kindle.images     https://www.gutenberg.org/ebooks/45.kindle.noimages     https://www.gutenberg.org/ebooks/45.txt.utf-8     https://www.gutenberg.org/files/45/45-h.zip               https://www.gutenberg.org/ebooks/45.rdf     https://www.gutenberg.org/files/45/45-h/45-h.htm ; https://www.gutenberg.org/files/45/45-0.zip ; https://www.gutenberg.org/files/45/45-0.txt ; https://www.gutenberg.org/cache/epub/45/pg45.cover.small.jpg ; https://www.gutenberg.org/cache/epub/45/pg45.cover.medium.jpg  1908              1
55            Text  1993-02-01  The Wonderful Wizard of Oz  en        PZ    Children's Literature; Fantasy; Browsing: Children & Young Adult Reading; Browsing: Science-Fiction & Fantasy; Browsing: Fiction                                 Baum, L. Frank (Lyman Frank)            Public domain in the USA.  Scarecrow (Fictitious character from Baum) -- Juvenile fiction ; Tin Woodman (Fictitious character) -- Juvenile fiction ; Gale, Dorothy (Fictitious character) -- Juvenile fiction ; Wizard of Oz (Fictitious character) -- Juvenile fiction ; Cowardly Lion (Fictitious character) -- Juvenile fiction ; Courage -- Juvenile fiction ; Oz (Imaginary place) -- Juvenile fiction ; PZ ; Cyclones -- Juvenile fiction ; Dreams -- Juvenile fiction ; Toto (Fictitious character) -- Juvenile fiction ; Home -- Juvenile fiction ; Witches -- Juvenile fiction ; Good and evil -- Juvenile fiction ; Fantasy literature  https://www.gutenberg.org/ebooks/55.html.images     https://www.gutenberg.org/ebooks/55.epub3.images     https://www.gutenberg.org/ebooks/55.epub.images     https://www.gutenberg.org/ebooks/55.epub.noimages     https://www.gutenberg.org/ebooks/55.kf8.images     https://www.gutenberg.org/ebooks/55.kindle.images     https://www.gutenberg.org/ebooks/55.kindle.noimages     https://www.gutenberg.org/ebooks/55.txt.utf-8     https://www.gutenberg.org/cache/epub/55/pg55-h.zip        https://www.gutenberg.org/ebooks/55.rdf     https://www.gutenberg.org/files/55/55-0.zip ; https://www.gutenberg.org/cache/epub/55/pg55.cover.small.jpg ; https://www.gutenberg.org/files/55/55-0.txt ; https://www.gutenberg.org/cache/epub/55/pg55.cover.medium.jpg ; https://www.gutenberg.org/files/55/55-h/55-h.htm  1900              1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ..
68930         Text  2022-09-07  Beyond the wall             en        PS    Browsing: Literature; Browsing: Fiction                                                                                                                          Leverage, Henry                         Public domain in the USA.  Short stories ; Orphans -- Fiction ; Fay, Chester (Fictitious character) -- Fiction ; PS ; Escaped prisoners -- Fiction ; Criminals -- Fiction                                                                                                                                                                                                                                                                                                                                                                                                                                                                         https://www.gutenberg.org/ebooks/68930.html.images  https://www.gutenberg.org/ebooks/68930.epub3.images  https://www.gutenberg.org/ebooks/68930.epub.images  https://www.gutenberg.org/ebooks/68930.epub.noimages  https://www.gutenberg.org/ebooks/68930.kf8.images  https://www.gutenberg.org/ebooks/68930.kindle.images  https://www.gutenberg.org/ebooks/68930.kindle.noimages  https://www.gutenberg.org/ebooks/68930.txt.utf-8  https://www.gutenberg.org/cache/epub/68930/pg68930-h.zip  https://www.gutenberg.org/ebooks/68930.rdf  https://www.gutenberg.org/cache/epub/68930/pg68930.cover.small.jpg ; https://www.gutenberg.org/files/68930/68930-0.txt ; https://www.gutenberg.org/files/68930/68930-h/68930-h.htm ; https://www.gutenberg.org/cache/epub/68930/pg68930.cover.medium.jpg                     1807              1
68939         Text  2022-09-08  The women novelists         en        PR    Browsing: Culture/Civilization/Society; Browsing: History - British; Browsing: Literature                                                                        Johnson, R. Brimley (Reginald Brimley)  Public domain in the USA.  English fiction -- 19th century -- History and criticism ; Women and literature -- Great Britain -- History ; English fiction -- 18th century -- History and criticism ; English fiction -- Women authors -- History and criticism ; PR                                                                                                                                                                                                                                                                                                                                                                                https://www.gutenberg.org/ebooks/68939.html.images  https://www.gutenberg.org/ebooks/68939.epub3.images  https://www.gutenberg.org/ebooks/68939.epub.images  https://www.gutenberg.org/ebooks/68939.epub.noimages  https://www.gutenberg.org/ebooks/68939.kf8.images  https://www.gutenberg.org/ebooks/68939.kindle.images  https://www.gutenberg.org/ebooks/68939.kindle.noimages  https://www.gutenberg.org/ebooks/68939.txt.utf-8  https://www.gutenberg.org/cache/epub/68939/pg68939-h.zip  https://www.gutenberg.org/ebooks/68939.rdf  https://www.gutenberg.org/cache/epub/68939/pg68939.cover.medium.jpg ; https://www.gutenberg.org/files/68939/68939-0.txt ; https://www.gutenberg.org/cache/epub/68939/pg68939.cover.small.jpg ; https://www.gutenberg.org/files/68939/68939-h/68939-h.htm                     1909              1
68966         Text  2022-09-11  The Snake's Pass            en        PR    Browsing: Culture/Civilization/Society; Browsing: Literature; Browsing: Fiction                                                                                  Stoker, Bram                            Public domain in the USA.  Ireland -- Social conditions -- Fiction ; Love stories ; PR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            https://www.gutenberg.org/ebooks/68966.html.images  https://www.gutenberg.org/ebooks/68966.epub3.images  https://www.gutenberg.org/ebooks/68966.epub.images  https://www.gutenberg.org/ebooks/68966.epub.noimages  https://www.gutenberg.org/ebooks/68966.kf8.images  https://www.gutenberg.org/ebooks/68966.kindle.images  https://www.gutenberg.org/ebooks/68966.kindle.noimages  https://www.gutenberg.org/ebooks/68966.txt.utf-8  https://www.gutenberg.org/cache/epub/68966/pg68966-h.zip  https://www.gutenberg.org/ebooks/68966.rdf  https://www.gutenberg.org/files/68966/68966-h/68966-h.htm ; https://www.gutenberg.org/cache/epub/68966/pg68966.cover.small.jpg ; https://www.gutenberg.org/files/68966/68966-0.txt ; https://www.gutenberg.org/cache/epub/68966/pg68966.cover.medium.jpg                     1897              1
68975         Text  2022-09-12  The crimp                   en        PS    Browsing: Literature; Browsing: Fiction                                                                                                                          Leverage, Henry                         Public domain in the USA.  Shanghaiing -- Fiction ; San Francisco (Calif.) -- Fiction ; PS ; Short stories                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        https://www.gutenberg.org/ebooks/68975.html.images  https://www.gutenberg.org/ebooks/68975.epub3.images  https://www.gutenberg.org/ebooks/68975.epub.images  https://www.gutenberg.org/ebooks/68975.epub.noimages  https://www.gutenberg.org/ebooks/68975.kf8.images  https://www.gutenberg.org/ebooks/68975.kindle.images  https://www.gutenberg.org/ebooks/68975.kindle.noimages  https://www.gutenberg.org/ebooks/68975.txt.utf-8  https://www.gutenberg.org/cache/epub/68975/pg68975-h.zip  https://www.gutenberg.org/ebooks/68975.rdf  https://www.gutenberg.org/cache/epub/68975/pg68975.cover.small.jpg ; https://www.gutenberg.org/files/68975/68975-0.txt ; https://www.gutenberg.org/cache/epub/68975/pg68975.cover.medium.jpg ; https://www.gutenberg.org/files/68975/68975-h/68975-h.htm                     1821              1

In [ ]:
#Clears kaggle cache on your machine, but you will need to reload the dataset next time
DELETE_KAGGELHUB_CACHE = False

if DELETE_KAGGELHUB_CACHE:
    # KaggleHub stores datasets here by default
    cache_path = os.path.expanduser("~/.cache/kagglehub/datasets/lokeshparab/gutenberg-books-and-metadata-2025")
    shutil.rmtree(cache_path)
    print("Deleted!")